// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AvatarWearWeaponSkinReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from AvatarWearWeaponSkinReq.proto</summary>
public static partial class AvatarWearWeaponSkinReqReflection {

  #region Descriptor
  /// <summary>File descriptor for AvatarWearWeaponSkinReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AvatarWearWeaponSkinReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch1BdmF0YXJXZWFyV2VhcG9uU2tpblJlcS5wcm90byJLChdBdmF0YXJXZWFy",
          "V2VhcG9uU2tpblJlcRIYChBhdmF0YXJfZ3VpZF9saXN0GAcgAygEEhYKDndl",
          "YXBvbl9za2luX2lkGA4gASgNQhsKGWVtdS5ncmFzc2N1dHRlci5uZXQucHJv",
          "dG9iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AvatarWearWeaponSkinReq), global::AvatarWearWeaponSkinReq.Parser, new[]{ "AvatarGuidList", "WeaponSkinId" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// version: 6.1
/// CmdID: 896
/// </summary>
public sealed partial class AvatarWearWeaponSkinReq : pb::IMessage<AvatarWearWeaponSkinReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AvatarWearWeaponSkinReq> _parser = new pb::MessageParser<AvatarWearWeaponSkinReq>(() => new AvatarWearWeaponSkinReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AvatarWearWeaponSkinReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AvatarWearWeaponSkinReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarWearWeaponSkinReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarWearWeaponSkinReq(AvatarWearWeaponSkinReq other) : this() {
    avatarGuidList_ = other.avatarGuidList_.Clone();
    weaponSkinId_ = other.weaponSkinId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarWearWeaponSkinReq Clone() {
    return new AvatarWearWeaponSkinReq(this);
  }

  /// <summary>Field number for the "avatar_guid_list" field.</summary>
  public const int AvatarGuidListFieldNumber = 7;
  private static readonly pb::FieldCodec<ulong> _repeated_avatarGuidList_codec
      = pb::FieldCodec.ForUInt64(58);
  private readonly pbc::RepeatedField<ulong> avatarGuidList_ = new pbc::RepeatedField<ulong>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<ulong> AvatarGuidList {
    get { return avatarGuidList_; }
  }

  /// <summary>Field number for the "weapon_skin_id" field.</summary>
  public const int WeaponSkinIdFieldNumber = 14;
  private uint weaponSkinId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint WeaponSkinId {
    get { return weaponSkinId_; }
    set {
      weaponSkinId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AvatarWearWeaponSkinReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AvatarWearWeaponSkinReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!avatarGuidList_.Equals(other.avatarGuidList_)) return false;
    if (WeaponSkinId != other.WeaponSkinId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= avatarGuidList_.GetHashCode();
    if (WeaponSkinId != 0) hash ^= WeaponSkinId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    avatarGuidList_.WriteTo(output, _repeated_avatarGuidList_codec);
    if (WeaponSkinId != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(WeaponSkinId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    avatarGuidList_.WriteTo(ref output, _repeated_avatarGuidList_codec);
    if (WeaponSkinId != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(WeaponSkinId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += avatarGuidList_.CalculateSize(_repeated_avatarGuidList_codec);
    if (WeaponSkinId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(WeaponSkinId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AvatarWearWeaponSkinReq other) {
    if (other == null) {
      return;
    }
    avatarGuidList_.Add(other.avatarGuidList_);
    if (other.WeaponSkinId != 0) {
      WeaponSkinId = other.WeaponSkinId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 58:
        case 56: {
          avatarGuidList_.AddEntriesFrom(input, _repeated_avatarGuidList_codec);
          break;
        }
        case 112: {
          WeaponSkinId = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 58:
        case 56: {
          avatarGuidList_.AddEntriesFrom(ref input, _repeated_avatarGuidList_codec);
          break;
        }
        case 112: {
          WeaponSkinId = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
