// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AvatarLifeStateChangeNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from AvatarLifeStateChangeNotify.proto</summary>
public static partial class AvatarLifeStateChangeNotifyReflection {

  #region Descriptor
  /// <summary>File descriptor for AvatarLifeStateChangeNotify.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static AvatarLifeStateChangeNotifyReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiFBdmF0YXJMaWZlU3RhdGVDaGFuZ2VOb3RpZnkucHJvdG8aE1BsYXllckRp",
          "ZVR5cGUucHJvdG8aEFNlcnZlckJ1ZmYucHJvdG8ilwIKG0F2YXRhckxpZmVT",
          "dGF0ZUNoYW5nZU5vdGlmeRITCgtQTERETlBHSEhCSBgPIAMoCRISCgphdHRh",
          "Y2tfdGFnGAsgASgJEiUKEHNlcnZlcl9idWZmX2xpc3QYCCADKAsyCy5TZXJ2",
          "ZXJCdWZmEiAKCGRpZV90eXBlGAMgASgOMg4uUGxheWVyRGllVHlwZRITCgtK",
          "RVBMQ0dNR01EUBgBIAEoDRITCgthdmF0YXJfZ3VpZBgFIAEoBBIZChFtb3Zl",
          "X3JlbGlhYmxlX3NlcRgJIAEoDRIYChBzb3VyY2VfZW50aXR5X2lkGAwgASgN",
          "EhIKCmxpZmVfc3RhdGUYAiABKA0SEwoLUE1KSUtFQkJERFAYBiABKA1CGwoZ",
          "ZW11LmdyYXNzY3V0dGVyLm5ldC5wcm90b2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::PlayerDieTypeReflection.Descriptor, global::ServerBuffReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::AvatarLifeStateChangeNotify), global::AvatarLifeStateChangeNotify.Parser, new[]{ "PLDDNPGHHBH", "AttackTag", "ServerBuffList", "DieType", "JEPLCGMGMDP", "AvatarGuid", "MoveReliableSeq", "SourceEntityId", "LifeState", "PMJIKEBBDDP" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.1
/// CmdID: 29857
/// </summary>
public sealed partial class AvatarLifeStateChangeNotify : pb::IMessage<AvatarLifeStateChangeNotify>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<AvatarLifeStateChangeNotify> _parser = new pb::MessageParser<AvatarLifeStateChangeNotify>(() => new AvatarLifeStateChangeNotify());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<AvatarLifeStateChangeNotify> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::AvatarLifeStateChangeNotifyReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarLifeStateChangeNotify() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarLifeStateChangeNotify(AvatarLifeStateChangeNotify other) : this() {
    pLDDNPGHHBH_ = other.pLDDNPGHHBH_.Clone();
    attackTag_ = other.attackTag_;
    serverBuffList_ = other.serverBuffList_.Clone();
    dieType_ = other.dieType_;
    jEPLCGMGMDP_ = other.jEPLCGMGMDP_;
    avatarGuid_ = other.avatarGuid_;
    moveReliableSeq_ = other.moveReliableSeq_;
    sourceEntityId_ = other.sourceEntityId_;
    lifeState_ = other.lifeState_;
    pMJIKEBBDDP_ = other.pMJIKEBBDDP_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public AvatarLifeStateChangeNotify Clone() {
    return new AvatarLifeStateChangeNotify(this);
  }

  /// <summary>Field number for the "PLDDNPGHHBH" field.</summary>
  public const int PLDDNPGHHBHFieldNumber = 15;
  private static readonly pb::FieldCodec<string> _repeated_pLDDNPGHHBH_codec
      = pb::FieldCodec.ForString(122);
  private readonly pbc::RepeatedField<string> pLDDNPGHHBH_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> PLDDNPGHHBH {
    get { return pLDDNPGHHBH_; }
  }

  /// <summary>Field number for the "attack_tag" field.</summary>
  public const int AttackTagFieldNumber = 11;
  private string attackTag_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string AttackTag {
    get { return attackTag_; }
    set {
      attackTag_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "server_buff_list" field.</summary>
  public const int ServerBuffListFieldNumber = 8;
  private static readonly pb::FieldCodec<global::ServerBuff> _repeated_serverBuffList_codec
      = pb::FieldCodec.ForMessage(66, global::ServerBuff.Parser);
  private readonly pbc::RepeatedField<global::ServerBuff> serverBuffList_ = new pbc::RepeatedField<global::ServerBuff>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::ServerBuff> ServerBuffList {
    get { return serverBuffList_; }
  }

  /// <summary>Field number for the "die_type" field.</summary>
  public const int DieTypeFieldNumber = 3;
  private global::PlayerDieType dieType_ = global::PlayerDieType.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::PlayerDieType DieType {
    get { return dieType_; }
    set {
      dieType_ = value;
    }
  }

  /// <summary>Field number for the "JEPLCGMGMDP" field.</summary>
  public const int JEPLCGMGMDPFieldNumber = 1;
  private uint jEPLCGMGMDP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint JEPLCGMGMDP {
    get { return jEPLCGMGMDP_; }
    set {
      jEPLCGMGMDP_ = value;
    }
  }

  /// <summary>Field number for the "avatar_guid" field.</summary>
  public const int AvatarGuidFieldNumber = 5;
  private ulong avatarGuid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong AvatarGuid {
    get { return avatarGuid_; }
    set {
      avatarGuid_ = value;
    }
  }

  /// <summary>Field number for the "move_reliable_seq" field.</summary>
  public const int MoveReliableSeqFieldNumber = 9;
  private uint moveReliableSeq_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MoveReliableSeq {
    get { return moveReliableSeq_; }
    set {
      moveReliableSeq_ = value;
    }
  }

  /// <summary>Field number for the "source_entity_id" field.</summary>
  public const int SourceEntityIdFieldNumber = 12;
  private uint sourceEntityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SourceEntityId {
    get { return sourceEntityId_; }
    set {
      sourceEntityId_ = value;
    }
  }

  /// <summary>Field number for the "life_state" field.</summary>
  public const int LifeStateFieldNumber = 2;
  private uint lifeState_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint LifeState {
    get { return lifeState_; }
    set {
      lifeState_ = value;
    }
  }

  /// <summary>Field number for the "PMJIKEBBDDP" field.</summary>
  public const int PMJIKEBBDDPFieldNumber = 6;
  private uint pMJIKEBBDDP_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint PMJIKEBBDDP {
    get { return pMJIKEBBDDP_; }
    set {
      pMJIKEBBDDP_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as AvatarLifeStateChangeNotify);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(AvatarLifeStateChangeNotify other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!pLDDNPGHHBH_.Equals(other.pLDDNPGHHBH_)) return false;
    if (AttackTag != other.AttackTag) return false;
    if(!serverBuffList_.Equals(other.serverBuffList_)) return false;
    if (DieType != other.DieType) return false;
    if (JEPLCGMGMDP != other.JEPLCGMGMDP) return false;
    if (AvatarGuid != other.AvatarGuid) return false;
    if (MoveReliableSeq != other.MoveReliableSeq) return false;
    if (SourceEntityId != other.SourceEntityId) return false;
    if (LifeState != other.LifeState) return false;
    if (PMJIKEBBDDP != other.PMJIKEBBDDP) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= pLDDNPGHHBH_.GetHashCode();
    if (AttackTag.Length != 0) hash ^= AttackTag.GetHashCode();
    hash ^= serverBuffList_.GetHashCode();
    if (DieType != global::PlayerDieType.None) hash ^= DieType.GetHashCode();
    if (JEPLCGMGMDP != 0) hash ^= JEPLCGMGMDP.GetHashCode();
    if (AvatarGuid != 0UL) hash ^= AvatarGuid.GetHashCode();
    if (MoveReliableSeq != 0) hash ^= MoveReliableSeq.GetHashCode();
    if (SourceEntityId != 0) hash ^= SourceEntityId.GetHashCode();
    if (LifeState != 0) hash ^= LifeState.GetHashCode();
    if (PMJIKEBBDDP != 0) hash ^= PMJIKEBBDDP.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (JEPLCGMGMDP != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(JEPLCGMGMDP);
    }
    if (LifeState != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(LifeState);
    }
    if (DieType != global::PlayerDieType.None) {
      output.WriteRawTag(24);
      output.WriteEnum((int) DieType);
    }
    if (AvatarGuid != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(AvatarGuid);
    }
    if (PMJIKEBBDDP != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(PMJIKEBBDDP);
    }
    serverBuffList_.WriteTo(output, _repeated_serverBuffList_codec);
    if (MoveReliableSeq != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(MoveReliableSeq);
    }
    if (AttackTag.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(AttackTag);
    }
    if (SourceEntityId != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(SourceEntityId);
    }
    pLDDNPGHHBH_.WriteTo(output, _repeated_pLDDNPGHHBH_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (JEPLCGMGMDP != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(JEPLCGMGMDP);
    }
    if (LifeState != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(LifeState);
    }
    if (DieType != global::PlayerDieType.None) {
      output.WriteRawTag(24);
      output.WriteEnum((int) DieType);
    }
    if (AvatarGuid != 0UL) {
      output.WriteRawTag(40);
      output.WriteUInt64(AvatarGuid);
    }
    if (PMJIKEBBDDP != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(PMJIKEBBDDP);
    }
    serverBuffList_.WriteTo(ref output, _repeated_serverBuffList_codec);
    if (MoveReliableSeq != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(MoveReliableSeq);
    }
    if (AttackTag.Length != 0) {
      output.WriteRawTag(90);
      output.WriteString(AttackTag);
    }
    if (SourceEntityId != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(SourceEntityId);
    }
    pLDDNPGHHBH_.WriteTo(ref output, _repeated_pLDDNPGHHBH_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += pLDDNPGHHBH_.CalculateSize(_repeated_pLDDNPGHHBH_codec);
    if (AttackTag.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(AttackTag);
    }
    size += serverBuffList_.CalculateSize(_repeated_serverBuffList_codec);
    if (DieType != global::PlayerDieType.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DieType);
    }
    if (JEPLCGMGMDP != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JEPLCGMGMDP);
    }
    if (AvatarGuid != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(AvatarGuid);
    }
    if (MoveReliableSeq != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MoveReliableSeq);
    }
    if (SourceEntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SourceEntityId);
    }
    if (LifeState != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LifeState);
    }
    if (PMJIKEBBDDP != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PMJIKEBBDDP);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(AvatarLifeStateChangeNotify other) {
    if (other == null) {
      return;
    }
    pLDDNPGHHBH_.Add(other.pLDDNPGHHBH_);
    if (other.AttackTag.Length != 0) {
      AttackTag = other.AttackTag;
    }
    serverBuffList_.Add(other.serverBuffList_);
    if (other.DieType != global::PlayerDieType.None) {
      DieType = other.DieType;
    }
    if (other.JEPLCGMGMDP != 0) {
      JEPLCGMGMDP = other.JEPLCGMGMDP;
    }
    if (other.AvatarGuid != 0UL) {
      AvatarGuid = other.AvatarGuid;
    }
    if (other.MoveReliableSeq != 0) {
      MoveReliableSeq = other.MoveReliableSeq;
    }
    if (other.SourceEntityId != 0) {
      SourceEntityId = other.SourceEntityId;
    }
    if (other.LifeState != 0) {
      LifeState = other.LifeState;
    }
    if (other.PMJIKEBBDDP != 0) {
      PMJIKEBBDDP = other.PMJIKEBBDDP;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          JEPLCGMGMDP = input.ReadUInt32();
          break;
        }
        case 16: {
          LifeState = input.ReadUInt32();
          break;
        }
        case 24: {
          DieType = (global::PlayerDieType) input.ReadEnum();
          break;
        }
        case 40: {
          AvatarGuid = input.ReadUInt64();
          break;
        }
        case 48: {
          PMJIKEBBDDP = input.ReadUInt32();
          break;
        }
        case 66: {
          serverBuffList_.AddEntriesFrom(input, _repeated_serverBuffList_codec);
          break;
        }
        case 72: {
          MoveReliableSeq = input.ReadUInt32();
          break;
        }
        case 90: {
          AttackTag = input.ReadString();
          break;
        }
        case 96: {
          SourceEntityId = input.ReadUInt32();
          break;
        }
        case 122: {
          pLDDNPGHHBH_.AddEntriesFrom(input, _repeated_pLDDNPGHHBH_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          JEPLCGMGMDP = input.ReadUInt32();
          break;
        }
        case 16: {
          LifeState = input.ReadUInt32();
          break;
        }
        case 24: {
          DieType = (global::PlayerDieType) input.ReadEnum();
          break;
        }
        case 40: {
          AvatarGuid = input.ReadUInt64();
          break;
        }
        case 48: {
          PMJIKEBBDDP = input.ReadUInt32();
          break;
        }
        case 66: {
          serverBuffList_.AddEntriesFrom(ref input, _repeated_serverBuffList_codec);
          break;
        }
        case 72: {
          MoveReliableSeq = input.ReadUInt32();
          break;
        }
        case 90: {
          AttackTag = input.ReadString();
          break;
        }
        case 96: {
          SourceEntityId = input.ReadUInt32();
          break;
        }
        case 122: {
          pLDDNPGHHBH_.AddEntriesFrom(ref input, _repeated_pLDDNPGHHBH_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
