// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BlossomBriefInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from BlossomBriefInfo.proto</summary>
public static partial class BlossomBriefInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for BlossomBriefInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BlossomBriefInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZCbG9zc29tQnJpZWZJbmZvLnByb3RvGgxWZWN0b3IucHJvdG8i7wEKEEJs",
          "b3Nzb21CcmllZkluZm8SFAoDcG9zGA8gASgLMgcuVmVjdG9yEhYKDmNpcmNs",
          "ZV9jYW1wX2lkGAMgASgNEg0KBXN0YXRlGAogASgNEhIKCnJlZnJlc2hfaWQY",
          "ASABKA0SFQoNbW9uc3Rlcl9sZXZlbBgOIAEoDRIQCghzY2VuZV9pZBgHIAEo",
          "DRIVCg1fbWFwX2xheWVyX2lkGAsgASgNEg8KB2NpdHlfaWQYAiABKA0SEQoJ",
          "cmV3YXJkX2lkGAYgASgNEhcKD2lzX2d1aWRlX29wZW5lZBgFIAEoCBINCgVy",
          "ZXNpbhgJIAEoDUIbChllbXUuZ3Jhc3NjdXR0ZXIubmV0LnByb3RvYgZwcm90",
          "bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::VectorReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BlossomBriefInfo), global::BlossomBriefInfo.Parser, new[]{ "Pos", "CircleCampId", "State", "RefreshId", "MonsterLevel", "SceneId", "MapLayerId", "CityId", "RewardId", "IsGuideOpened", "Resin" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.1
/// </summary>
public sealed partial class BlossomBriefInfo : pb::IMessage<BlossomBriefInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BlossomBriefInfo> _parser = new pb::MessageParser<BlossomBriefInfo>(() => new BlossomBriefInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BlossomBriefInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BlossomBriefInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BlossomBriefInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BlossomBriefInfo(BlossomBriefInfo other) : this() {
    pos_ = other.pos_ != null ? other.pos_.Clone() : null;
    circleCampId_ = other.circleCampId_;
    state_ = other.state_;
    refreshId_ = other.refreshId_;
    monsterLevel_ = other.monsterLevel_;
    sceneId_ = other.sceneId_;
    MapLayerId_ = other.MapLayerId_;
    cityId_ = other.cityId_;
    rewardId_ = other.rewardId_;
    isGuideOpened_ = other.isGuideOpened_;
    resin_ = other.resin_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BlossomBriefInfo Clone() {
    return new BlossomBriefInfo(this);
  }

  /// <summary>Field number for the "pos" field.</summary>
  public const int PosFieldNumber = 15;
  private global::Vector pos_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Vector Pos {
    get { return pos_; }
    set {
      pos_ = value;
    }
  }

  /// <summary>Field number for the "circle_camp_id" field.</summary>
  public const int CircleCampIdFieldNumber = 3;
  private uint circleCampId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CircleCampId {
    get { return circleCampId_; }
    set {
      circleCampId_ = value;
    }
  }

  /// <summary>Field number for the "state" field.</summary>
  public const int StateFieldNumber = 10;
  private uint state_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint State {
    get { return state_; }
    set {
      state_ = value;
    }
  }

  /// <summary>Field number for the "refresh_id" field.</summary>
  public const int RefreshIdFieldNumber = 1;
  private uint refreshId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RefreshId {
    get { return refreshId_; }
    set {
      refreshId_ = value;
    }
  }

  /// <summary>Field number for the "monster_level" field.</summary>
  public const int MonsterLevelFieldNumber = 14;
  private uint monsterLevel_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MonsterLevel {
    get { return monsterLevel_; }
    set {
      monsterLevel_ = value;
    }
  }

  /// <summary>Field number for the "scene_id" field.</summary>
  public const int SceneIdFieldNumber = 7;
  private uint sceneId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint SceneId {
    get { return sceneId_; }
    set {
      sceneId_ = value;
    }
  }

  /// <summary>Field number for the "_map_layer_id" field.</summary>
  public const int MapLayerIdFieldNumber = 11;
  private uint MapLayerId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MapLayerId {
    get { return MapLayerId_; }
    set {
      MapLayerId_ = value;
    }
  }

  /// <summary>Field number for the "city_id" field.</summary>
  public const int CityIdFieldNumber = 2;
  private uint cityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CityId {
    get { return cityId_; }
    set {
      cityId_ = value;
    }
  }

  /// <summary>Field number for the "reward_id" field.</summary>
  public const int RewardIdFieldNumber = 6;
  private uint rewardId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint RewardId {
    get { return rewardId_; }
    set {
      rewardId_ = value;
    }
  }

  /// <summary>Field number for the "is_guide_opened" field.</summary>
  public const int IsGuideOpenedFieldNumber = 5;
  private bool isGuideOpened_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsGuideOpened {
    get { return isGuideOpened_; }
    set {
      isGuideOpened_ = value;
    }
  }

  /// <summary>Field number for the "resin" field.</summary>
  public const int ResinFieldNumber = 9;
  private uint resin_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Resin {
    get { return resin_; }
    set {
      resin_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BlossomBriefInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BlossomBriefInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(Pos, other.Pos)) return false;
    if (CircleCampId != other.CircleCampId) return false;
    if (State != other.State) return false;
    if (RefreshId != other.RefreshId) return false;
    if (MonsterLevel != other.MonsterLevel) return false;
    if (SceneId != other.SceneId) return false;
    if (MapLayerId != other.MapLayerId) return false;
    if (CityId != other.CityId) return false;
    if (RewardId != other.RewardId) return false;
    if (IsGuideOpened != other.IsGuideOpened) return false;
    if (Resin != other.Resin) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (pos_ != null) hash ^= Pos.GetHashCode();
    if (CircleCampId != 0) hash ^= CircleCampId.GetHashCode();
    if (State != 0) hash ^= State.GetHashCode();
    if (RefreshId != 0) hash ^= RefreshId.GetHashCode();
    if (MonsterLevel != 0) hash ^= MonsterLevel.GetHashCode();
    if (SceneId != 0) hash ^= SceneId.GetHashCode();
    if (MapLayerId != 0) hash ^= MapLayerId.GetHashCode();
    if (CityId != 0) hash ^= CityId.GetHashCode();
    if (RewardId != 0) hash ^= RewardId.GetHashCode();
    if (IsGuideOpened != false) hash ^= IsGuideOpened.GetHashCode();
    if (Resin != 0) hash ^= Resin.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (RefreshId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(RefreshId);
    }
    if (CityId != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(CityId);
    }
    if (CircleCampId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(CircleCampId);
    }
    if (IsGuideOpened != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsGuideOpened);
    }
    if (RewardId != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(RewardId);
    }
    if (SceneId != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(SceneId);
    }
    if (Resin != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(Resin);
    }
    if (State != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(State);
    }
    if (MapLayerId != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(MapLayerId);
    }
    if (MonsterLevel != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(MonsterLevel);
    }
    if (pos_ != null) {
      output.WriteRawTag(122);
      output.WriteMessage(Pos);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (RefreshId != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(RefreshId);
    }
    if (CityId != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(CityId);
    }
    if (CircleCampId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(CircleCampId);
    }
    if (IsGuideOpened != false) {
      output.WriteRawTag(40);
      output.WriteBool(IsGuideOpened);
    }
    if (RewardId != 0) {
      output.WriteRawTag(48);
      output.WriteUInt32(RewardId);
    }
    if (SceneId != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(SceneId);
    }
    if (Resin != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(Resin);
    }
    if (State != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(State);
    }
    if (MapLayerId != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(MapLayerId);
    }
    if (MonsterLevel != 0) {
      output.WriteRawTag(112);
      output.WriteUInt32(MonsterLevel);
    }
    if (pos_ != null) {
      output.WriteRawTag(122);
      output.WriteMessage(Pos);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (pos_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pos);
    }
    if (CircleCampId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CircleCampId);
    }
    if (State != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(State);
    }
    if (RefreshId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RefreshId);
    }
    if (MonsterLevel != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MonsterLevel);
    }
    if (SceneId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SceneId);
    }
    if (MapLayerId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MapLayerId);
    }
    if (CityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CityId);
    }
    if (RewardId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RewardId);
    }
    if (IsGuideOpened != false) {
      size += 1 + 1;
    }
    if (Resin != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Resin);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BlossomBriefInfo other) {
    if (other == null) {
      return;
    }
    if (other.pos_ != null) {
      if (pos_ == null) {
        Pos = new global::Vector();
      }
      Pos.MergeFrom(other.Pos);
    }
    if (other.CircleCampId != 0) {
      CircleCampId = other.CircleCampId;
    }
    if (other.State != 0) {
      State = other.State;
    }
    if (other.RefreshId != 0) {
      RefreshId = other.RefreshId;
    }
    if (other.MonsterLevel != 0) {
      MonsterLevel = other.MonsterLevel;
    }
    if (other.SceneId != 0) {
      SceneId = other.SceneId;
    }
    if (other.MapLayerId != 0) {
      MapLayerId = other.MapLayerId;
    }
    if (other.CityId != 0) {
      CityId = other.CityId;
    }
    if (other.RewardId != 0) {
      RewardId = other.RewardId;
    }
    if (other.IsGuideOpened != false) {
      IsGuideOpened = other.IsGuideOpened;
    }
    if (other.Resin != 0) {
      Resin = other.Resin;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          RefreshId = input.ReadUInt32();
          break;
        }
        case 16: {
          CityId = input.ReadUInt32();
          break;
        }
        case 24: {
          CircleCampId = input.ReadUInt32();
          break;
        }
        case 40: {
          IsGuideOpened = input.ReadBool();
          break;
        }
        case 48: {
          RewardId = input.ReadUInt32();
          break;
        }
        case 56: {
          SceneId = input.ReadUInt32();
          break;
        }
        case 72: {
          Resin = input.ReadUInt32();
          break;
        }
        case 80: {
          State = input.ReadUInt32();
          break;
        }
        case 88: {
          MapLayerId = input.ReadUInt32();
          break;
        }
        case 112: {
          MonsterLevel = input.ReadUInt32();
          break;
        }
        case 122: {
          if (pos_ == null) {
            Pos = new global::Vector();
          }
          input.ReadMessage(Pos);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          RefreshId = input.ReadUInt32();
          break;
        }
        case 16: {
          CityId = input.ReadUInt32();
          break;
        }
        case 24: {
          CircleCampId = input.ReadUInt32();
          break;
        }
        case 40: {
          IsGuideOpened = input.ReadBool();
          break;
        }
        case 48: {
          RewardId = input.ReadUInt32();
          break;
        }
        case 56: {
          SceneId = input.ReadUInt32();
          break;
        }
        case 72: {
          Resin = input.ReadUInt32();
          break;
        }
        case 80: {
          State = input.ReadUInt32();
          break;
        }
        case 88: {
          MapLayerId = input.ReadUInt32();
          break;
        }
        case 112: {
          MonsterLevel = input.ReadUInt32();
          break;
        }
        case 122: {
          if (pos_ == null) {
            Pos = new global::Vector();
          }
          input.ReadMessage(Pos);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
