// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BreakoutBrickInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from BreakoutBrickInfo.proto</summary>
public static partial class BreakoutBrickInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for BreakoutBrickInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BreakoutBrickInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdCcmVha291dEJyaWNrSW5mby5wcm90byJKChFCcmVha291dEJyaWNrSW5m",
          "bxIUCgxlbGVtZW50X3R5cGUYAiABKA0SEwoLRkRMQUpBTEtBQ0MYAyABKA0S",
          "CgoCaHAYASABKA1CGwoZZW11LmdyYXNzY3V0dGVyLm5ldC5wcm90b2IGcHJv",
          "dG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BreakoutBrickInfo), global::BreakoutBrickInfo.Parser, new[]{ "ElementType", "FDLAJALKACC", "Hp" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.0.0
/// </summary>
public sealed partial class BreakoutBrickInfo : pb::IMessage<BreakoutBrickInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BreakoutBrickInfo> _parser = new pb::MessageParser<BreakoutBrickInfo>(() => new BreakoutBrickInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BreakoutBrickInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BreakoutBrickInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutBrickInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutBrickInfo(BreakoutBrickInfo other) : this() {
    elementType_ = other.elementType_;
    fDLAJALKACC_ = other.fDLAJALKACC_;
    hp_ = other.hp_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutBrickInfo Clone() {
    return new BreakoutBrickInfo(this);
  }

  /// <summary>Field number for the "element_type" field.</summary>
  public const int ElementTypeFieldNumber = 2;
  private uint elementType_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ElementType {
    get { return elementType_; }
    set {
      elementType_ = value;
    }
  }

  /// <summary>Field number for the "FDLAJALKACC" field.</summary>
  public const int FDLAJALKACCFieldNumber = 3;
  private uint fDLAJALKACC_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint FDLAJALKACC {
    get { return fDLAJALKACC_; }
    set {
      fDLAJALKACC_ = value;
    }
  }

  /// <summary>Field number for the "hp" field.</summary>
  public const int HpFieldNumber = 1;
  private uint hp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Hp {
    get { return hp_; }
    set {
      hp_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BreakoutBrickInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BreakoutBrickInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ElementType != other.ElementType) return false;
    if (FDLAJALKACC != other.FDLAJALKACC) return false;
    if (Hp != other.Hp) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ElementType != 0) hash ^= ElementType.GetHashCode();
    if (FDLAJALKACC != 0) hash ^= FDLAJALKACC.GetHashCode();
    if (Hp != 0) hash ^= Hp.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Hp != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Hp);
    }
    if (ElementType != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(ElementType);
    }
    if (FDLAJALKACC != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(FDLAJALKACC);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Hp != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Hp);
    }
    if (ElementType != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(ElementType);
    }
    if (FDLAJALKACC != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(FDLAJALKACC);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ElementType != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ElementType);
    }
    if (FDLAJALKACC != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FDLAJALKACC);
    }
    if (Hp != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Hp);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BreakoutBrickInfo other) {
    if (other == null) {
      return;
    }
    if (other.ElementType != 0) {
      ElementType = other.ElementType;
    }
    if (other.FDLAJALKACC != 0) {
      FDLAJALKACC = other.FDLAJALKACC;
    }
    if (other.Hp != 0) {
      Hp = other.Hp;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Hp = input.ReadUInt32();
          break;
        }
        case 16: {
          ElementType = input.ReadUInt32();
          break;
        }
        case 24: {
          FDLAJALKACC = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Hp = input.ReadUInt32();
          break;
        }
        case 16: {
          ElementType = input.ReadUInt32();
          break;
        }
        case 24: {
          FDLAJALKACC = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
