// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BreakoutSpawnPoint.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from BreakoutSpawnPoint.proto</summary>
public static partial class BreakoutSpawnPointReflection {

  #region Descriptor
  /// <summary>File descriptor for BreakoutSpawnPoint.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BreakoutSpawnPointReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhCcmVha291dFNwYXduUG9pbnQucHJvdG8aHEJyZWFrb3V0UGh5c2ljYWxP",
          "YmplY3QucHJvdG8irAEKEkJyZWFrb3V0U3Bhd25Qb2ludBIWCg5pbnRfcGFy",
          "YW1fbGlzdBgHIAMoBRIzChJzcGF3bmVkX2JyaWNrX2xpc3QYAyADKAsyFy5C",
          "cmVha291dFBoeXNpY2FsT2JqZWN0EhMKC01ESEdCUEdMT0ZJGAQgASgNEhMK",
          "C0xPTEhOSUJMQ0dIGAIgASgNEgoKAmlkGAEgASgNEhMKC01DRkFQUExLTkRJ",
          "GAUgASgNQhsKGWVtdS5ncmFzc2N1dHRlci5uZXQucHJvdG9iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::BreakoutPhysicalObjectReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BreakoutSpawnPoint), global::BreakoutSpawnPoint.Parser, new[]{ "IntParamList", "SpawnedBrickList", "MDHGBPGLOFI", "LOLHNIBLCGH", "Id", "MCFAPPLKNDI" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.0.0
/// </summary>
public sealed partial class BreakoutSpawnPoint : pb::IMessage<BreakoutSpawnPoint>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<BreakoutSpawnPoint> _parser = new pb::MessageParser<BreakoutSpawnPoint>(() => new BreakoutSpawnPoint());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<BreakoutSpawnPoint> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BreakoutSpawnPointReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutSpawnPoint() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutSpawnPoint(BreakoutSpawnPoint other) : this() {
    intParamList_ = other.intParamList_.Clone();
    spawnedBrickList_ = other.spawnedBrickList_.Clone();
    mDHGBPGLOFI_ = other.mDHGBPGLOFI_;
    lOLHNIBLCGH_ = other.lOLHNIBLCGH_;
    id_ = other.id_;
    mCFAPPLKNDI_ = other.mCFAPPLKNDI_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public BreakoutSpawnPoint Clone() {
    return new BreakoutSpawnPoint(this);
  }

  /// <summary>Field number for the "int_param_list" field.</summary>
  public const int IntParamListFieldNumber = 7;
  private static readonly pb::FieldCodec<int> _repeated_intParamList_codec
      = pb::FieldCodec.ForInt32(58);
  private readonly pbc::RepeatedField<int> intParamList_ = new pbc::RepeatedField<int>();
  /// <summary>
  /// repeated GJCGOAIMPCK EEGFNOAOKOO = 6;
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<int> IntParamList {
    get { return intParamList_; }
  }

  /// <summary>Field number for the "spawned_brick_list" field.</summary>
  public const int SpawnedBrickListFieldNumber = 3;
  private static readonly pb::FieldCodec<global::BreakoutPhysicalObject> _repeated_spawnedBrickList_codec
      = pb::FieldCodec.ForMessage(26, global::BreakoutPhysicalObject.Parser);
  private readonly pbc::RepeatedField<global::BreakoutPhysicalObject> spawnedBrickList_ = new pbc::RepeatedField<global::BreakoutPhysicalObject>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::BreakoutPhysicalObject> SpawnedBrickList {
    get { return spawnedBrickList_; }
  }

  /// <summary>Field number for the "MDHGBPGLOFI" field.</summary>
  public const int MDHGBPGLOFIFieldNumber = 4;
  private uint mDHGBPGLOFI_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MDHGBPGLOFI {
    get { return mDHGBPGLOFI_; }
    set {
      mDHGBPGLOFI_ = value;
    }
  }

  /// <summary>Field number for the "LOLHNIBLCGH" field.</summary>
  public const int LOLHNIBLCGHFieldNumber = 2;
  private uint lOLHNIBLCGH_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint LOLHNIBLCGH {
    get { return lOLHNIBLCGH_; }
    set {
      lOLHNIBLCGH_ = value;
    }
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private uint id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "MCFAPPLKNDI" field.</summary>
  public const int MCFAPPLKNDIFieldNumber = 5;
  private uint mCFAPPLKNDI_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MCFAPPLKNDI {
    get { return mCFAPPLKNDI_; }
    set {
      mCFAPPLKNDI_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as BreakoutSpawnPoint);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(BreakoutSpawnPoint other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!intParamList_.Equals(other.intParamList_)) return false;
    if(!spawnedBrickList_.Equals(other.spawnedBrickList_)) return false;
    if (MDHGBPGLOFI != other.MDHGBPGLOFI) return false;
    if (LOLHNIBLCGH != other.LOLHNIBLCGH) return false;
    if (Id != other.Id) return false;
    if (MCFAPPLKNDI != other.MCFAPPLKNDI) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= intParamList_.GetHashCode();
    hash ^= spawnedBrickList_.GetHashCode();
    if (MDHGBPGLOFI != 0) hash ^= MDHGBPGLOFI.GetHashCode();
    if (LOLHNIBLCGH != 0) hash ^= LOLHNIBLCGH.GetHashCode();
    if (Id != 0) hash ^= Id.GetHashCode();
    if (MCFAPPLKNDI != 0) hash ^= MCFAPPLKNDI.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (LOLHNIBLCGH != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(LOLHNIBLCGH);
    }
    spawnedBrickList_.WriteTo(output, _repeated_spawnedBrickList_codec);
    if (MDHGBPGLOFI != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(MDHGBPGLOFI);
    }
    if (MCFAPPLKNDI != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(MCFAPPLKNDI);
    }
    intParamList_.WriteTo(output, _repeated_intParamList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Id);
    }
    if (LOLHNIBLCGH != 0) {
      output.WriteRawTag(16);
      output.WriteUInt32(LOLHNIBLCGH);
    }
    spawnedBrickList_.WriteTo(ref output, _repeated_spawnedBrickList_codec);
    if (MDHGBPGLOFI != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(MDHGBPGLOFI);
    }
    if (MCFAPPLKNDI != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(MCFAPPLKNDI);
    }
    intParamList_.WriteTo(ref output, _repeated_intParamList_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += intParamList_.CalculateSize(_repeated_intParamList_codec);
    size += spawnedBrickList_.CalculateSize(_repeated_spawnedBrickList_codec);
    if (MDHGBPGLOFI != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MDHGBPGLOFI);
    }
    if (LOLHNIBLCGH != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LOLHNIBLCGH);
    }
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Id);
    }
    if (MCFAPPLKNDI != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MCFAPPLKNDI);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(BreakoutSpawnPoint other) {
    if (other == null) {
      return;
    }
    intParamList_.Add(other.intParamList_);
    spawnedBrickList_.Add(other.spawnedBrickList_);
    if (other.MDHGBPGLOFI != 0) {
      MDHGBPGLOFI = other.MDHGBPGLOFI;
    }
    if (other.LOLHNIBLCGH != 0) {
      LOLHNIBLCGH = other.LOLHNIBLCGH;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.MCFAPPLKNDI != 0) {
      MCFAPPLKNDI = other.MCFAPPLKNDI;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          LOLHNIBLCGH = input.ReadUInt32();
          break;
        }
        case 26: {
          spawnedBrickList_.AddEntriesFrom(input, _repeated_spawnedBrickList_codec);
          break;
        }
        case 32: {
          MDHGBPGLOFI = input.ReadUInt32();
          break;
        }
        case 40: {
          MCFAPPLKNDI = input.ReadUInt32();
          break;
        }
        case 58:
        case 56: {
          intParamList_.AddEntriesFrom(input, _repeated_intParamList_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadUInt32();
          break;
        }
        case 16: {
          LOLHNIBLCGH = input.ReadUInt32();
          break;
        }
        case 26: {
          spawnedBrickList_.AddEntriesFrom(ref input, _repeated_spawnedBrickList_codec);
          break;
        }
        case 32: {
          MDHGBPGLOFI = input.ReadUInt32();
          break;
        }
        case 40: {
          MCFAPPLKNDI = input.ReadUInt32();
          break;
        }
        case 58:
        case 56: {
          intParamList_.AddEntriesFrom(ref input, _repeated_intParamList_codec);
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
