// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CooperateChallengeDungeonSettleInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from CooperateChallengeDungeonSettleInfo.proto</summary>
public static partial class CooperateChallengeDungeonSettleInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for CooperateChallengeDungeonSettleInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CooperateChallengeDungeonSettleInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CilDb29wZXJhdGVDaGFsbGVuZ2VEdW5nZW9uU2V0dGxlSW5mby5wcm90bxob",
          "RXhoaWJpdGlvbkRpc3BsYXlJbmZvLnByb3RvGhRQcm9maWxlUGljdHVyZS5w",
          "cm90byLyBQojQ29vcGVyYXRlQ2hhbGxlbmdlRHVuZ2VvblNldHRsZUluZm8S",
          "RQoLUE5CRkdFR0lHRkwYDSADKAsyMC5Db29wZXJhdGVDaGFsbGVuZ2VEdW5n",
          "ZW9uU2V0dGxlSW5mby5PR0JPTEVDRUdHQRJFCgtITUdGTUlHTUNJTxgFIAMo",
          "CzIwLkNvb3BlcmF0ZUNoYWxsZW5nZUR1bmdlb25TZXR0bGVJbmZvLkVBTkJB",
          "QU9MR0NEEhMKC0hOTUZJQ09JQktBGAQgASgNEhUKDWRpZmZpY3VsdHlfaWQY",
          "CiABKA0SRQoLSktNTUlNQ0VGT00YDCABKA4yMC5Db29wZXJhdGVDaGFsbGVu",
          "Z2VEdW5nZW9uU2V0dGxlSW5mby5BUENHUEJHRkhLRBITCgtKRkdOSFBDREhG",
          "TBgJIAMoDRpJCgtFQU5CQUFPTEdDRBITCgtNRElETUpEQklOThgOIAEoBRIT",
          "CgtITEFJUEVKQ0FHQhgCIAEoDRIQCgh1aWRfbGlzdBgHIAMoDRrgAQoLT0dC",
          "T0xFQ0VHR0ESEwoLUEFGRUtFUEdIQUsYAiABKAkSEQoJb25saW5lX2lkGA4g",
          "ASgJEhAKCG5pY2tuYW1lGAMgASgJEhEKCWFkZF9zY29yZRgHIAEoDRINCgVz",
          "Y29yZRgEIAEoDRILCgN1aWQYCiABKA0SKAoPcHJvZmlsZV9waWN0dXJlGAsg",
          "ASgLMg8uUHJvZmlsZVBpY3R1cmUSEwoLRU1BSkxPR1BHSlAYBiADKA0SKQoJ",
          "Y2FyZF9saXN0GAUgAygLMhYuRXhoaWJpdGlvbkRpc3BsYXlJbmZvIoYBCgtB",
          "UENHUEJHRkhLRBIiCh5BUENHUEJHRkhLRF9TRVRUTEVfUkVBU09OX05PTkUQ",
          "ABIiCh5BUENHUEJHRkhLRF9TRVRUTEVfUkVBU09OX1NVQ0MQARIvCitBUENH",
          "UEJHRkhLRF9TRVRUTEVfUkVBU09OX1BMQVlFUl9OT1RfRU5PVUdIEAJCGwoZ",
          "ZW11LmdyYXNzY3V0dGVyLm5ldC5wcm90b2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::ExhibitionDisplayInfoReflection.Descriptor, global::ProfilePictureReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::CooperateChallengeDungeonSettleInfo), global::CooperateChallengeDungeonSettleInfo.Parser, new[]{ "PNBFGEGIGFL", "HMGFMIGMCIO", "HNMFICOIBKA", "DifficultyId", "JKMMIMCEFOM", "JFGNHPCDHFL" }, null, new[]{ typeof(global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::CooperateChallengeDungeonSettleInfo.Types.EANBAAOLGCD), global::CooperateChallengeDungeonSettleInfo.Types.EANBAAOLGCD.Parser, new[]{ "MDIDMJDBINN", "HLAIPEJCAGB", "UidList" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::CooperateChallengeDungeonSettleInfo.Types.OGBOLECEGGA), global::CooperateChallengeDungeonSettleInfo.Types.OGBOLECEGGA.Parser, new[]{ "PAFEKEPGHAK", "OnlineId", "Nickname", "AddScore", "Score", "Uid", "ProfilePicture", "EMAJLOGPGJP", "CardList" }, null, null, null, null)})
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.0
/// </summary>
public sealed partial class CooperateChallengeDungeonSettleInfo : pb::IMessage<CooperateChallengeDungeonSettleInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<CooperateChallengeDungeonSettleInfo> _parser = new pb::MessageParser<CooperateChallengeDungeonSettleInfo>(() => new CooperateChallengeDungeonSettleInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<CooperateChallengeDungeonSettleInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CooperateChallengeDungeonSettleInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CooperateChallengeDungeonSettleInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CooperateChallengeDungeonSettleInfo(CooperateChallengeDungeonSettleInfo other) : this() {
    pNBFGEGIGFL_ = other.pNBFGEGIGFL_.Clone();
    hMGFMIGMCIO_ = other.hMGFMIGMCIO_.Clone();
    hNMFICOIBKA_ = other.hNMFICOIBKA_;
    difficultyId_ = other.difficultyId_;
    jKMMIMCEFOM_ = other.jKMMIMCEFOM_;
    jFGNHPCDHFL_ = other.jFGNHPCDHFL_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public CooperateChallengeDungeonSettleInfo Clone() {
    return new CooperateChallengeDungeonSettleInfo(this);
  }

  /// <summary>Field number for the "PNBFGEGIGFL" field.</summary>
  public const int PNBFGEGIGFLFieldNumber = 13;
  private static readonly pb::FieldCodec<global::CooperateChallengeDungeonSettleInfo.Types.OGBOLECEGGA> _repeated_pNBFGEGIGFL_codec
      = pb::FieldCodec.ForMessage(106, global::CooperateChallengeDungeonSettleInfo.Types.OGBOLECEGGA.Parser);
  private readonly pbc::RepeatedField<global::CooperateChallengeDungeonSettleInfo.Types.OGBOLECEGGA> pNBFGEGIGFL_ = new pbc::RepeatedField<global::CooperateChallengeDungeonSettleInfo.Types.OGBOLECEGGA>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::CooperateChallengeDungeonSettleInfo.Types.OGBOLECEGGA> PNBFGEGIGFL {
    get { return pNBFGEGIGFL_; }
  }

  /// <summary>Field number for the "HMGFMIGMCIO" field.</summary>
  public const int HMGFMIGMCIOFieldNumber = 5;
  private static readonly pb::FieldCodec<global::CooperateChallengeDungeonSettleInfo.Types.EANBAAOLGCD> _repeated_hMGFMIGMCIO_codec
      = pb::FieldCodec.ForMessage(42, global::CooperateChallengeDungeonSettleInfo.Types.EANBAAOLGCD.Parser);
  private readonly pbc::RepeatedField<global::CooperateChallengeDungeonSettleInfo.Types.EANBAAOLGCD> hMGFMIGMCIO_ = new pbc::RepeatedField<global::CooperateChallengeDungeonSettleInfo.Types.EANBAAOLGCD>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::CooperateChallengeDungeonSettleInfo.Types.EANBAAOLGCD> HMGFMIGMCIO {
    get { return hMGFMIGMCIO_; }
  }

  /// <summary>Field number for the "HNMFICOIBKA" field.</summary>
  public const int HNMFICOIBKAFieldNumber = 4;
  private uint hNMFICOIBKA_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint HNMFICOIBKA {
    get { return hNMFICOIBKA_; }
    set {
      hNMFICOIBKA_ = value;
    }
  }

  /// <summary>Field number for the "difficulty_id" field.</summary>
  public const int DifficultyIdFieldNumber = 10;
  private uint difficultyId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint DifficultyId {
    get { return difficultyId_; }
    set {
      difficultyId_ = value;
    }
  }

  /// <summary>Field number for the "JKMMIMCEFOM" field.</summary>
  public const int JKMMIMCEFOMFieldNumber = 12;
  private global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD jKMMIMCEFOM_ = global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD.SettleReasonNone;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD JKMMIMCEFOM {
    get { return jKMMIMCEFOM_; }
    set {
      jKMMIMCEFOM_ = value;
    }
  }

  /// <summary>Field number for the "JFGNHPCDHFL" field.</summary>
  public const int JFGNHPCDHFLFieldNumber = 9;
  private static readonly pb::FieldCodec<uint> _repeated_jFGNHPCDHFL_codec
      = pb::FieldCodec.ForUInt32(74);
  private readonly pbc::RepeatedField<uint> jFGNHPCDHFL_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<uint> JFGNHPCDHFL {
    get { return jFGNHPCDHFL_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as CooperateChallengeDungeonSettleInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(CooperateChallengeDungeonSettleInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!pNBFGEGIGFL_.Equals(other.pNBFGEGIGFL_)) return false;
    if(!hMGFMIGMCIO_.Equals(other.hMGFMIGMCIO_)) return false;
    if (HNMFICOIBKA != other.HNMFICOIBKA) return false;
    if (DifficultyId != other.DifficultyId) return false;
    if (JKMMIMCEFOM != other.JKMMIMCEFOM) return false;
    if(!jFGNHPCDHFL_.Equals(other.jFGNHPCDHFL_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= pNBFGEGIGFL_.GetHashCode();
    hash ^= hMGFMIGMCIO_.GetHashCode();
    if (HNMFICOIBKA != 0) hash ^= HNMFICOIBKA.GetHashCode();
    if (DifficultyId != 0) hash ^= DifficultyId.GetHashCode();
    if (JKMMIMCEFOM != global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD.SettleReasonNone) hash ^= JKMMIMCEFOM.GetHashCode();
    hash ^= jFGNHPCDHFL_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HNMFICOIBKA != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(HNMFICOIBKA);
    }
    hMGFMIGMCIO_.WriteTo(output, _repeated_hMGFMIGMCIO_codec);
    jFGNHPCDHFL_.WriteTo(output, _repeated_jFGNHPCDHFL_codec);
    if (DifficultyId != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(DifficultyId);
    }
    if (JKMMIMCEFOM != global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD.SettleReasonNone) {
      output.WriteRawTag(96);
      output.WriteEnum((int) JKMMIMCEFOM);
    }
    pNBFGEGIGFL_.WriteTo(output, _repeated_pNBFGEGIGFL_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HNMFICOIBKA != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(HNMFICOIBKA);
    }
    hMGFMIGMCIO_.WriteTo(ref output, _repeated_hMGFMIGMCIO_codec);
    jFGNHPCDHFL_.WriteTo(ref output, _repeated_jFGNHPCDHFL_codec);
    if (DifficultyId != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(DifficultyId);
    }
    if (JKMMIMCEFOM != global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD.SettleReasonNone) {
      output.WriteRawTag(96);
      output.WriteEnum((int) JKMMIMCEFOM);
    }
    pNBFGEGIGFL_.WriteTo(ref output, _repeated_pNBFGEGIGFL_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += pNBFGEGIGFL_.CalculateSize(_repeated_pNBFGEGIGFL_codec);
    size += hMGFMIGMCIO_.CalculateSize(_repeated_hMGFMIGMCIO_codec);
    if (HNMFICOIBKA != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HNMFICOIBKA);
    }
    if (DifficultyId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DifficultyId);
    }
    if (JKMMIMCEFOM != global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD.SettleReasonNone) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) JKMMIMCEFOM);
    }
    size += jFGNHPCDHFL_.CalculateSize(_repeated_jFGNHPCDHFL_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(CooperateChallengeDungeonSettleInfo other) {
    if (other == null) {
      return;
    }
    pNBFGEGIGFL_.Add(other.pNBFGEGIGFL_);
    hMGFMIGMCIO_.Add(other.hMGFMIGMCIO_);
    if (other.HNMFICOIBKA != 0) {
      HNMFICOIBKA = other.HNMFICOIBKA;
    }
    if (other.DifficultyId != 0) {
      DifficultyId = other.DifficultyId;
    }
    if (other.JKMMIMCEFOM != global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD.SettleReasonNone) {
      JKMMIMCEFOM = other.JKMMIMCEFOM;
    }
    jFGNHPCDHFL_.Add(other.jFGNHPCDHFL_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 32: {
          HNMFICOIBKA = input.ReadUInt32();
          break;
        }
        case 42: {
          hMGFMIGMCIO_.AddEntriesFrom(input, _repeated_hMGFMIGMCIO_codec);
          break;
        }
        case 74:
        case 72: {
          jFGNHPCDHFL_.AddEntriesFrom(input, _repeated_jFGNHPCDHFL_codec);
          break;
        }
        case 80: {
          DifficultyId = input.ReadUInt32();
          break;
        }
        case 96: {
          JKMMIMCEFOM = (global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD) input.ReadEnum();
          break;
        }
        case 106: {
          pNBFGEGIGFL_.AddEntriesFrom(input, _repeated_pNBFGEGIGFL_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 32: {
          HNMFICOIBKA = input.ReadUInt32();
          break;
        }
        case 42: {
          hMGFMIGMCIO_.AddEntriesFrom(ref input, _repeated_hMGFMIGMCIO_codec);
          break;
        }
        case 74:
        case 72: {
          jFGNHPCDHFL_.AddEntriesFrom(ref input, _repeated_jFGNHPCDHFL_codec);
          break;
        }
        case 80: {
          DifficultyId = input.ReadUInt32();
          break;
        }
        case 96: {
          JKMMIMCEFOM = (global::CooperateChallengeDungeonSettleInfo.Types.APCGPBGFHKD) input.ReadEnum();
          break;
        }
        case 106: {
          pNBFGEGIGFL_.AddEntriesFrom(ref input, _repeated_pNBFGEGIGFL_codec);
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the CooperateChallengeDungeonSettleInfo message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    public enum APCGPBGFHKD {
      [pbr::OriginalName("APCGPBGFHKD_SETTLE_REASON_NONE")] SettleReasonNone = 0,
      [pbr::OriginalName("APCGPBGFHKD_SETTLE_REASON_SUCC")] SettleReasonSucc = 1,
      [pbr::OriginalName("APCGPBGFHKD_SETTLE_REASON_PLAYER_NOT_ENOUGH")] SettleReasonPlayerNotEnough = 2,
    }

    public sealed partial class EANBAAOLGCD : pb::IMessage<EANBAAOLGCD>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<EANBAAOLGCD> _parser = new pb::MessageParser<EANBAAOLGCD>(() => new EANBAAOLGCD());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<EANBAAOLGCD> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::CooperateChallengeDungeonSettleInfo.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public EANBAAOLGCD() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public EANBAAOLGCD(EANBAAOLGCD other) : this() {
        mDIDMJDBINN_ = other.mDIDMJDBINN_;
        hLAIPEJCAGB_ = other.hLAIPEJCAGB_;
        uidList_ = other.uidList_.Clone();
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public EANBAAOLGCD Clone() {
        return new EANBAAOLGCD(this);
      }

      /// <summary>Field number for the "MDIDMJDBINN" field.</summary>
      public const int MDIDMJDBINNFieldNumber = 14;
      private int mDIDMJDBINN_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int MDIDMJDBINN {
        get { return mDIDMJDBINN_; }
        set {
          mDIDMJDBINN_ = value;
        }
      }

      /// <summary>Field number for the "HLAIPEJCAGB" field.</summary>
      public const int HLAIPEJCAGBFieldNumber = 2;
      private uint hLAIPEJCAGB_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint HLAIPEJCAGB {
        get { return hLAIPEJCAGB_; }
        set {
          hLAIPEJCAGB_ = value;
        }
      }

      /// <summary>Field number for the "uid_list" field.</summary>
      public const int UidListFieldNumber = 7;
      private static readonly pb::FieldCodec<uint> _repeated_uidList_codec
          = pb::FieldCodec.ForUInt32(58);
      private readonly pbc::RepeatedField<uint> uidList_ = new pbc::RepeatedField<uint>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<uint> UidList {
        get { return uidList_; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as EANBAAOLGCD);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(EANBAAOLGCD other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (MDIDMJDBINN != other.MDIDMJDBINN) return false;
        if (HLAIPEJCAGB != other.HLAIPEJCAGB) return false;
        if(!uidList_.Equals(other.uidList_)) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (MDIDMJDBINN != 0) hash ^= MDIDMJDBINN.GetHashCode();
        if (HLAIPEJCAGB != 0) hash ^= HLAIPEJCAGB.GetHashCode();
        hash ^= uidList_.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (HLAIPEJCAGB != 0) {
          output.WriteRawTag(16);
          output.WriteUInt32(HLAIPEJCAGB);
        }
        uidList_.WriteTo(output, _repeated_uidList_codec);
        if (MDIDMJDBINN != 0) {
          output.WriteRawTag(112);
          output.WriteInt32(MDIDMJDBINN);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (HLAIPEJCAGB != 0) {
          output.WriteRawTag(16);
          output.WriteUInt32(HLAIPEJCAGB);
        }
        uidList_.WriteTo(ref output, _repeated_uidList_codec);
        if (MDIDMJDBINN != 0) {
          output.WriteRawTag(112);
          output.WriteInt32(MDIDMJDBINN);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (MDIDMJDBINN != 0) {
          size += 1 + pb::CodedOutputStream.ComputeInt32Size(MDIDMJDBINN);
        }
        if (HLAIPEJCAGB != 0) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HLAIPEJCAGB);
        }
        size += uidList_.CalculateSize(_repeated_uidList_codec);
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(EANBAAOLGCD other) {
        if (other == null) {
          return;
        }
        if (other.MDIDMJDBINN != 0) {
          MDIDMJDBINN = other.MDIDMJDBINN;
        }
        if (other.HLAIPEJCAGB != 0) {
          HLAIPEJCAGB = other.HLAIPEJCAGB;
        }
        uidList_.Add(other.uidList_);
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 16: {
              HLAIPEJCAGB = input.ReadUInt32();
              break;
            }
            case 58:
            case 56: {
              uidList_.AddEntriesFrom(input, _repeated_uidList_codec);
              break;
            }
            case 112: {
              MDIDMJDBINN = input.ReadInt32();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 16: {
              HLAIPEJCAGB = input.ReadUInt32();
              break;
            }
            case 58:
            case 56: {
              uidList_.AddEntriesFrom(ref input, _repeated_uidList_codec);
              break;
            }
            case 112: {
              MDIDMJDBINN = input.ReadInt32();
              break;
            }
          }
        }
      }
      #endif

    }

    public sealed partial class OGBOLECEGGA : pb::IMessage<OGBOLECEGGA>
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
    #endif
    {
      private static readonly pb::MessageParser<OGBOLECEGGA> _parser = new pb::MessageParser<OGBOLECEGGA>(() => new OGBOLECEGGA());
      private pb::UnknownFieldSet _unknownFields;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pb::MessageParser<OGBOLECEGGA> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::CooperateChallengeDungeonSettleInfo.Descriptor.NestedTypes[1]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OGBOLECEGGA() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OGBOLECEGGA(OGBOLECEGGA other) : this() {
        pAFEKEPGHAK_ = other.pAFEKEPGHAK_;
        onlineId_ = other.onlineId_;
        nickname_ = other.nickname_;
        addScore_ = other.addScore_;
        score_ = other.score_;
        uid_ = other.uid_;
        profilePicture_ = other.profilePicture_ != null ? other.profilePicture_.Clone() : null;
        eMAJLOGPGJP_ = other.eMAJLOGPGJP_.Clone();
        cardList_ = other.cardList_.Clone();
        _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public OGBOLECEGGA Clone() {
        return new OGBOLECEGGA(this);
      }

      /// <summary>Field number for the "PAFEKEPGHAK" field.</summary>
      public const int PAFEKEPGHAKFieldNumber = 2;
      private string pAFEKEPGHAK_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string PAFEKEPGHAK {
        get { return pAFEKEPGHAK_; }
        set {
          pAFEKEPGHAK_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      /// <summary>Field number for the "online_id" field.</summary>
      public const int OnlineIdFieldNumber = 14;
      private string onlineId_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string OnlineId {
        get { return onlineId_; }
        set {
          onlineId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      /// <summary>Field number for the "nickname" field.</summary>
      public const int NicknameFieldNumber = 3;
      private string nickname_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public string Nickname {
        get { return nickname_; }
        set {
          nickname_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      /// <summary>Field number for the "add_score" field.</summary>
      public const int AddScoreFieldNumber = 7;
      private uint addScore_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint AddScore {
        get { return addScore_; }
        set {
          addScore_ = value;
        }
      }

      /// <summary>Field number for the "score" field.</summary>
      public const int ScoreFieldNumber = 4;
      private uint score_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint Score {
        get { return score_; }
        set {
          score_ = value;
        }
      }

      /// <summary>Field number for the "uid" field.</summary>
      public const int UidFieldNumber = 10;
      private uint uid_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public uint Uid {
        get { return uid_; }
        set {
          uid_ = value;
        }
      }

      /// <summary>Field number for the "profile_picture" field.</summary>
      public const int ProfilePictureFieldNumber = 11;
      private global::ProfilePicture profilePicture_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public global::ProfilePicture ProfilePicture {
        get { return profilePicture_; }
        set {
          profilePicture_ = value;
        }
      }

      /// <summary>Field number for the "EMAJLOGPGJP" field.</summary>
      public const int EMAJLOGPGJPFieldNumber = 6;
      private static readonly pb::FieldCodec<uint> _repeated_eMAJLOGPGJP_codec
          = pb::FieldCodec.ForUInt32(50);
      private readonly pbc::RepeatedField<uint> eMAJLOGPGJP_ = new pbc::RepeatedField<uint>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<uint> EMAJLOGPGJP {
        get { return eMAJLOGPGJP_; }
      }

      /// <summary>Field number for the "card_list" field.</summary>
      public const int CardListFieldNumber = 5;
      private static readonly pb::FieldCodec<global::ExhibitionDisplayInfo> _repeated_cardList_codec
          = pb::FieldCodec.ForMessage(42, global::ExhibitionDisplayInfo.Parser);
      private readonly pbc::RepeatedField<global::ExhibitionDisplayInfo> cardList_ = new pbc::RepeatedField<global::ExhibitionDisplayInfo>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public pbc::RepeatedField<global::ExhibitionDisplayInfo> CardList {
        get { return cardList_; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override bool Equals(object other) {
        return Equals(other as OGBOLECEGGA);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public bool Equals(OGBOLECEGGA other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (PAFEKEPGHAK != other.PAFEKEPGHAK) return false;
        if (OnlineId != other.OnlineId) return false;
        if (Nickname != other.Nickname) return false;
        if (AddScore != other.AddScore) return false;
        if (Score != other.Score) return false;
        if (Uid != other.Uid) return false;
        if (!object.Equals(ProfilePicture, other.ProfilePicture)) return false;
        if(!eMAJLOGPGJP_.Equals(other.eMAJLOGPGJP_)) return false;
        if(!cardList_.Equals(other.cardList_)) return false;
        return Equals(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override int GetHashCode() {
        int hash = 1;
        if (PAFEKEPGHAK.Length != 0) hash ^= PAFEKEPGHAK.GetHashCode();
        if (OnlineId.Length != 0) hash ^= OnlineId.GetHashCode();
        if (Nickname.Length != 0) hash ^= Nickname.GetHashCode();
        if (AddScore != 0) hash ^= AddScore.GetHashCode();
        if (Score != 0) hash ^= Score.GetHashCode();
        if (Uid != 0) hash ^= Uid.GetHashCode();
        if (profilePicture_ != null) hash ^= ProfilePicture.GetHashCode();
        hash ^= eMAJLOGPGJP_.GetHashCode();
        hash ^= cardList_.GetHashCode();
        if (_unknownFields != null) {
          hash ^= _unknownFields.GetHashCode();
        }
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void WriteTo(pb::CodedOutputStream output) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        output.WriteRawMessage(this);
      #else
        if (PAFEKEPGHAK.Length != 0) {
          output.WriteRawTag(18);
          output.WriteString(PAFEKEPGHAK);
        }
        if (Nickname.Length != 0) {
          output.WriteRawTag(26);
          output.WriteString(Nickname);
        }
        if (Score != 0) {
          output.WriteRawTag(32);
          output.WriteUInt32(Score);
        }
        cardList_.WriteTo(output, _repeated_cardList_codec);
        eMAJLOGPGJP_.WriteTo(output, _repeated_eMAJLOGPGJP_codec);
        if (AddScore != 0) {
          output.WriteRawTag(56);
          output.WriteUInt32(AddScore);
        }
        if (Uid != 0) {
          output.WriteRawTag(80);
          output.WriteUInt32(Uid);
        }
        if (profilePicture_ != null) {
          output.WriteRawTag(90);
          output.WriteMessage(ProfilePicture);
        }
        if (OnlineId.Length != 0) {
          output.WriteRawTag(114);
          output.WriteString(OnlineId);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(output);
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
        if (PAFEKEPGHAK.Length != 0) {
          output.WriteRawTag(18);
          output.WriteString(PAFEKEPGHAK);
        }
        if (Nickname.Length != 0) {
          output.WriteRawTag(26);
          output.WriteString(Nickname);
        }
        if (Score != 0) {
          output.WriteRawTag(32);
          output.WriteUInt32(Score);
        }
        cardList_.WriteTo(ref output, _repeated_cardList_codec);
        eMAJLOGPGJP_.WriteTo(ref output, _repeated_eMAJLOGPGJP_codec);
        if (AddScore != 0) {
          output.WriteRawTag(56);
          output.WriteUInt32(AddScore);
        }
        if (Uid != 0) {
          output.WriteRawTag(80);
          output.WriteUInt32(Uid);
        }
        if (profilePicture_ != null) {
          output.WriteRawTag(90);
          output.WriteMessage(ProfilePicture);
        }
        if (OnlineId.Length != 0) {
          output.WriteRawTag(114);
          output.WriteString(OnlineId);
        }
        if (_unknownFields != null) {
          _unknownFields.WriteTo(ref output);
        }
      }
      #endif

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public int CalculateSize() {
        int size = 0;
        if (PAFEKEPGHAK.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(PAFEKEPGHAK);
        }
        if (OnlineId.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(OnlineId);
        }
        if (Nickname.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Nickname);
        }
        if (AddScore != 0) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AddScore);
        }
        if (Score != 0) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Score);
        }
        if (Uid != 0) {
          size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uid);
        }
        if (profilePicture_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(ProfilePicture);
        }
        size += eMAJLOGPGJP_.CalculateSize(_repeated_eMAJLOGPGJP_codec);
        size += cardList_.CalculateSize(_repeated_cardList_codec);
        if (_unknownFields != null) {
          size += _unknownFields.CalculateSize();
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(OGBOLECEGGA other) {
        if (other == null) {
          return;
        }
        if (other.PAFEKEPGHAK.Length != 0) {
          PAFEKEPGHAK = other.PAFEKEPGHAK;
        }
        if (other.OnlineId.Length != 0) {
          OnlineId = other.OnlineId;
        }
        if (other.Nickname.Length != 0) {
          Nickname = other.Nickname;
        }
        if (other.AddScore != 0) {
          AddScore = other.AddScore;
        }
        if (other.Score != 0) {
          Score = other.Score;
        }
        if (other.Uid != 0) {
          Uid = other.Uid;
        }
        if (other.profilePicture_ != null) {
          if (profilePicture_ == null) {
            ProfilePicture = new global::ProfilePicture();
          }
          ProfilePicture.MergeFrom(other.ProfilePicture);
        }
        eMAJLOGPGJP_.Add(other.eMAJLOGPGJP_);
        cardList_.Add(other.cardList_);
        _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      public void MergeFrom(pb::CodedInputStream input) {
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        input.ReadRawMessage(this);
      #else
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
              break;
            case 18: {
              PAFEKEPGHAK = input.ReadString();
              break;
            }
            case 26: {
              Nickname = input.ReadString();
              break;
            }
            case 32: {
              Score = input.ReadUInt32();
              break;
            }
            case 42: {
              cardList_.AddEntriesFrom(input, _repeated_cardList_codec);
              break;
            }
            case 50:
            case 48: {
              eMAJLOGPGJP_.AddEntriesFrom(input, _repeated_eMAJLOGPGJP_codec);
              break;
            }
            case 56: {
              AddScore = input.ReadUInt32();
              break;
            }
            case 80: {
              Uid = input.ReadUInt32();
              break;
            }
            case 90: {
              if (profilePicture_ == null) {
                ProfilePicture = new global::ProfilePicture();
              }
              input.ReadMessage(ProfilePicture);
              break;
            }
            case 114: {
              OnlineId = input.ReadString();
              break;
            }
          }
        }
      #endif
      }

      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
      void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
              break;
            case 18: {
              PAFEKEPGHAK = input.ReadString();
              break;
            }
            case 26: {
              Nickname = input.ReadString();
              break;
            }
            case 32: {
              Score = input.ReadUInt32();
              break;
            }
            case 42: {
              cardList_.AddEntriesFrom(ref input, _repeated_cardList_codec);
              break;
            }
            case 50:
            case 48: {
              eMAJLOGPGJP_.AddEntriesFrom(ref input, _repeated_eMAJLOGPGJP_codec);
              break;
            }
            case 56: {
              AddScore = input.ReadUInt32();
              break;
            }
            case 80: {
              Uid = input.ReadUInt32();
              break;
            }
            case 90: {
              if (profilePicture_ == null) {
                ProfilePicture = new global::ProfilePicture();
              }
              input.ReadMessage(ProfilePicture);
              break;
            }
            case 114: {
              OnlineId = input.ReadString();
              break;
            }
          }
        }
      }
      #endif

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
