// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: DetailAbilityInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from DetailAbilityInfo.proto</summary>
public static partial class DetailAbilityInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for DetailAbilityInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static DetailAbilityInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdEZXRhaWxBYmlsaXR5SW5mby5wcm90bxoTQWJpbGl0eVN0cmluZy5wcm90",
          "byK9AQoRRGV0YWlsQWJpbGl0eUluZm8SKwoTcGFyZW50X2FiaWxpdHlfbmFt",
          "ZRgMIAEoCzIOLkFiaWxpdHlTdHJpbmcSHQoVaW5zdGFuY2VkX21vZGlmaWVy",
          "X2lkGA0gASgNEhEKCWNhc3Rlcl9pZBgHIAEoDRIZChFtb2RpZmllcl9sb2Nh",
          "bF9pZBgKIAEoBRIcChRpbnN0YW5jZWRfYWJpbGl0eV9pZBgEIAEoDRIQCghs",
          "b2NhbF9pZBgOIAEoBUIbChllbXUuZ3Jhc3NjdXR0ZXIubmV0LnByb3RvYgZw",
          "cm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::AbilityStringReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::DetailAbilityInfo), global::DetailAbilityInfo.Parser, new[]{ "ParentAbilityName", "InstancedModifierId", "CasterId", "ModifierLocalId", "InstancedAbilityId", "LocalId" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.1
/// </summary>
public sealed partial class DetailAbilityInfo : pb::IMessage<DetailAbilityInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<DetailAbilityInfo> _parser = new pb::MessageParser<DetailAbilityInfo>(() => new DetailAbilityInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<DetailAbilityInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::DetailAbilityInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DetailAbilityInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DetailAbilityInfo(DetailAbilityInfo other) : this() {
    parentAbilityName_ = other.parentAbilityName_ != null ? other.parentAbilityName_.Clone() : null;
    instancedModifierId_ = other.instancedModifierId_;
    casterId_ = other.casterId_;
    modifierLocalId_ = other.modifierLocalId_;
    instancedAbilityId_ = other.instancedAbilityId_;
    localId_ = other.localId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public DetailAbilityInfo Clone() {
    return new DetailAbilityInfo(this);
  }

  /// <summary>Field number for the "parent_ability_name" field.</summary>
  public const int ParentAbilityNameFieldNumber = 12;
  private global::AbilityString parentAbilityName_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::AbilityString ParentAbilityName {
    get { return parentAbilityName_; }
    set {
      parentAbilityName_ = value;
    }
  }

  /// <summary>Field number for the "instanced_modifier_id" field.</summary>
  public const int InstancedModifierIdFieldNumber = 13;
  private uint instancedModifierId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint InstancedModifierId {
    get { return instancedModifierId_; }
    set {
      instancedModifierId_ = value;
    }
  }

  /// <summary>Field number for the "caster_id" field.</summary>
  public const int CasterIdFieldNumber = 7;
  private uint casterId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint CasterId {
    get { return casterId_; }
    set {
      casterId_ = value;
    }
  }

  /// <summary>Field number for the "modifier_local_id" field.</summary>
  public const int ModifierLocalIdFieldNumber = 10;
  private int modifierLocalId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int ModifierLocalId {
    get { return modifierLocalId_; }
    set {
      modifierLocalId_ = value;
    }
  }

  /// <summary>Field number for the "instanced_ability_id" field.</summary>
  public const int InstancedAbilityIdFieldNumber = 4;
  private uint instancedAbilityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint InstancedAbilityId {
    get { return instancedAbilityId_; }
    set {
      instancedAbilityId_ = value;
    }
  }

  /// <summary>Field number for the "local_id" field.</summary>
  public const int LocalIdFieldNumber = 14;
  private int localId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int LocalId {
    get { return localId_; }
    set {
      localId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as DetailAbilityInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(DetailAbilityInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(ParentAbilityName, other.ParentAbilityName)) return false;
    if (InstancedModifierId != other.InstancedModifierId) return false;
    if (CasterId != other.CasterId) return false;
    if (ModifierLocalId != other.ModifierLocalId) return false;
    if (InstancedAbilityId != other.InstancedAbilityId) return false;
    if (LocalId != other.LocalId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (parentAbilityName_ != null) hash ^= ParentAbilityName.GetHashCode();
    if (InstancedModifierId != 0) hash ^= InstancedModifierId.GetHashCode();
    if (CasterId != 0) hash ^= CasterId.GetHashCode();
    if (ModifierLocalId != 0) hash ^= ModifierLocalId.GetHashCode();
    if (InstancedAbilityId != 0) hash ^= InstancedAbilityId.GetHashCode();
    if (LocalId != 0) hash ^= LocalId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (InstancedAbilityId != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(InstancedAbilityId);
    }
    if (CasterId != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(CasterId);
    }
    if (ModifierLocalId != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(ModifierLocalId);
    }
    if (parentAbilityName_ != null) {
      output.WriteRawTag(98);
      output.WriteMessage(ParentAbilityName);
    }
    if (InstancedModifierId != 0) {
      output.WriteRawTag(104);
      output.WriteUInt32(InstancedModifierId);
    }
    if (LocalId != 0) {
      output.WriteRawTag(112);
      output.WriteInt32(LocalId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (InstancedAbilityId != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(InstancedAbilityId);
    }
    if (CasterId != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(CasterId);
    }
    if (ModifierLocalId != 0) {
      output.WriteRawTag(80);
      output.WriteInt32(ModifierLocalId);
    }
    if (parentAbilityName_ != null) {
      output.WriteRawTag(98);
      output.WriteMessage(ParentAbilityName);
    }
    if (InstancedModifierId != 0) {
      output.WriteRawTag(104);
      output.WriteUInt32(InstancedModifierId);
    }
    if (LocalId != 0) {
      output.WriteRawTag(112);
      output.WriteInt32(LocalId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (parentAbilityName_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(ParentAbilityName);
    }
    if (InstancedModifierId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InstancedModifierId);
    }
    if (CasterId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CasterId);
    }
    if (ModifierLocalId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ModifierLocalId);
    }
    if (InstancedAbilityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(InstancedAbilityId);
    }
    if (LocalId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(LocalId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(DetailAbilityInfo other) {
    if (other == null) {
      return;
    }
    if (other.parentAbilityName_ != null) {
      if (parentAbilityName_ == null) {
        ParentAbilityName = new global::AbilityString();
      }
      ParentAbilityName.MergeFrom(other.ParentAbilityName);
    }
    if (other.InstancedModifierId != 0) {
      InstancedModifierId = other.InstancedModifierId;
    }
    if (other.CasterId != 0) {
      CasterId = other.CasterId;
    }
    if (other.ModifierLocalId != 0) {
      ModifierLocalId = other.ModifierLocalId;
    }
    if (other.InstancedAbilityId != 0) {
      InstancedAbilityId = other.InstancedAbilityId;
    }
    if (other.LocalId != 0) {
      LocalId = other.LocalId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 32: {
          InstancedAbilityId = input.ReadUInt32();
          break;
        }
        case 56: {
          CasterId = input.ReadUInt32();
          break;
        }
        case 80: {
          ModifierLocalId = input.ReadInt32();
          break;
        }
        case 98: {
          if (parentAbilityName_ == null) {
            ParentAbilityName = new global::AbilityString();
          }
          input.ReadMessage(ParentAbilityName);
          break;
        }
        case 104: {
          InstancedModifierId = input.ReadUInt32();
          break;
        }
        case 112: {
          LocalId = input.ReadInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 32: {
          InstancedAbilityId = input.ReadUInt32();
          break;
        }
        case 56: {
          CasterId = input.ReadUInt32();
          break;
        }
        case 80: {
          ModifierLocalId = input.ReadInt32();
          break;
        }
        case 98: {
          if (parentAbilityName_ == null) {
            ParentAbilityName = new global::AbilityString();
          }
          input.ReadMessage(ParentAbilityName);
          break;
        }
        case 104: {
          InstancedModifierId = input.ReadUInt32();
          break;
        }
        case 112: {
          LocalId = input.ReadInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
