// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EvtAvatarEnterFocusNotify.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from EvtAvatarEnterFocusNotify.proto</summary>
public static partial class EvtAvatarEnterFocusNotifyReflection {

  #region Descriptor
  /// <summary>File descriptor for EvtAvatarEnterFocusNotify.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EvtAvatarEnterFocusNotifyReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch9FdnRBdmF0YXJFbnRlckZvY3VzTm90aWZ5LnByb3RvGgxWZWN0b3IucHJv",
          "dG8aEUZvcndhcmRUeXBlLnByb3RvItkCChlFdnRBdmF0YXJFbnRlckZvY3Vz",
          "Tm90aWZ5Eh4KDWZvY3VzX2ZvcndhcmQYDiABKAsyBy5WZWN0b3ISEwoLS0RQ",
          "RkxGT1BJSUoYCyABKAgSEwoLQUtCSUlBSE9ITEIYByABKAgSEwoLSEdLUEFN",
          "RE9KRkcYCiABKAgSEwoLRUNNQ05GREtFQ04YDCABKAgSIgoMZm9yd2FyZF90",
          "eXBlGAYgASgOMgwuRm9yd2FyZFR5cGUSEwoLTk9HTktLSkFJSkMYAyABKAUS",
          "EQoJZW50aXR5X2lkGAggASgNEhMKC0RKR0hBSEpBSUxHGAkgASgIEhMKC09P",
          "R0VJT0NERU5KGAIgASgIEhMKC0NJSEdKSkxORklOGA0gASgIEhMKC0dCRUVP",
          "SEdJQ0FOGAEgASgIEhMKC0dCTkpCTk9OSUdDGA8gASgIEhMKC01PSUtBTkRK",
          "UE1KGAQgASgIQhsKGWVtdS5ncmFzc2N1dHRlci5uZXQucHJvdG9iBnByb3Rv",
          "Mw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::VectorReflection.Descriptor, global::ForwardTypeReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::EvtAvatarEnterFocusNotify), global::EvtAvatarEnterFocusNotify.Parser, new[]{ "FocusForward", "KDPFLFOPIIJ", "AKBIIAHOHLB", "HGKPAMDOJFG", "ECMCNFDKECN", "ForwardType", "NOGNKKJAIJC", "EntityId", "DJGHAHJAILG", "OOGEIOCDENJ", "CIHGJJLNFIN", "GBEEOHGICAN", "GBNJBNONIGC", "MOIKANDJPMJ" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.1
/// CmdID: 29028
/// </summary>
public sealed partial class EvtAvatarEnterFocusNotify : pb::IMessage<EvtAvatarEnterFocusNotify>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<EvtAvatarEnterFocusNotify> _parser = new pb::MessageParser<EvtAvatarEnterFocusNotify>(() => new EvtAvatarEnterFocusNotify());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<EvtAvatarEnterFocusNotify> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::EvtAvatarEnterFocusNotifyReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EvtAvatarEnterFocusNotify() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EvtAvatarEnterFocusNotify(EvtAvatarEnterFocusNotify other) : this() {
    focusForward_ = other.focusForward_ != null ? other.focusForward_.Clone() : null;
    kDPFLFOPIIJ_ = other.kDPFLFOPIIJ_;
    aKBIIAHOHLB_ = other.aKBIIAHOHLB_;
    hGKPAMDOJFG_ = other.hGKPAMDOJFG_;
    eCMCNFDKECN_ = other.eCMCNFDKECN_;
    forwardType_ = other.forwardType_;
    nOGNKKJAIJC_ = other.nOGNKKJAIJC_;
    entityId_ = other.entityId_;
    dJGHAHJAILG_ = other.dJGHAHJAILG_;
    oOGEIOCDENJ_ = other.oOGEIOCDENJ_;
    cIHGJJLNFIN_ = other.cIHGJJLNFIN_;
    gBEEOHGICAN_ = other.gBEEOHGICAN_;
    gBNJBNONIGC_ = other.gBNJBNONIGC_;
    mOIKANDJPMJ_ = other.mOIKANDJPMJ_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public EvtAvatarEnterFocusNotify Clone() {
    return new EvtAvatarEnterFocusNotify(this);
  }

  /// <summary>Field number for the "focus_forward" field.</summary>
  public const int FocusForwardFieldNumber = 14;
  private global::Vector focusForward_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::Vector FocusForward {
    get { return focusForward_; }
    set {
      focusForward_ = value;
    }
  }

  /// <summary>Field number for the "KDPFLFOPIIJ" field.</summary>
  public const int KDPFLFOPIIJFieldNumber = 11;
  private bool kDPFLFOPIIJ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool KDPFLFOPIIJ {
    get { return kDPFLFOPIIJ_; }
    set {
      kDPFLFOPIIJ_ = value;
    }
  }

  /// <summary>Field number for the "AKBIIAHOHLB" field.</summary>
  public const int AKBIIAHOHLBFieldNumber = 7;
  private bool aKBIIAHOHLB_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool AKBIIAHOHLB {
    get { return aKBIIAHOHLB_; }
    set {
      aKBIIAHOHLB_ = value;
    }
  }

  /// <summary>Field number for the "HGKPAMDOJFG" field.</summary>
  public const int HGKPAMDOJFGFieldNumber = 10;
  private bool hGKPAMDOJFG_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HGKPAMDOJFG {
    get { return hGKPAMDOJFG_; }
    set {
      hGKPAMDOJFG_ = value;
    }
  }

  /// <summary>Field number for the "ECMCNFDKECN" field.</summary>
  public const int ECMCNFDKECNFieldNumber = 12;
  private bool eCMCNFDKECN_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool ECMCNFDKECN {
    get { return eCMCNFDKECN_; }
    set {
      eCMCNFDKECN_ = value;
    }
  }

  /// <summary>Field number for the "forward_type" field.</summary>
  public const int ForwardTypeFieldNumber = 6;
  private global::ForwardType forwardType_ = global::ForwardType.ForwardLocal;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ForwardType ForwardType {
    get { return forwardType_; }
    set {
      forwardType_ = value;
    }
  }

  /// <summary>Field number for the "NOGNKKJAIJC" field.</summary>
  public const int NOGNKKJAIJCFieldNumber = 3;
  private int nOGNKKJAIJC_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int NOGNKKJAIJC {
    get { return nOGNKKJAIJC_; }
    set {
      nOGNKKJAIJC_ = value;
    }
  }

  /// <summary>Field number for the "entity_id" field.</summary>
  public const int EntityIdFieldNumber = 8;
  private uint entityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint EntityId {
    get { return entityId_; }
    set {
      entityId_ = value;
    }
  }

  /// <summary>Field number for the "DJGHAHJAILG" field.</summary>
  public const int DJGHAHJAILGFieldNumber = 9;
  private bool dJGHAHJAILG_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool DJGHAHJAILG {
    get { return dJGHAHJAILG_; }
    set {
      dJGHAHJAILG_ = value;
    }
  }

  /// <summary>Field number for the "OOGEIOCDENJ" field.</summary>
  public const int OOGEIOCDENJFieldNumber = 2;
  private bool oOGEIOCDENJ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool OOGEIOCDENJ {
    get { return oOGEIOCDENJ_; }
    set {
      oOGEIOCDENJ_ = value;
    }
  }

  /// <summary>Field number for the "CIHGJJLNFIN" field.</summary>
  public const int CIHGJJLNFINFieldNumber = 13;
  private bool cIHGJJLNFIN_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool CIHGJJLNFIN {
    get { return cIHGJJLNFIN_; }
    set {
      cIHGJJLNFIN_ = value;
    }
  }

  /// <summary>Field number for the "GBEEOHGICAN" field.</summary>
  public const int GBEEOHGICANFieldNumber = 1;
  private bool gBEEOHGICAN_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool GBEEOHGICAN {
    get { return gBEEOHGICAN_; }
    set {
      gBEEOHGICAN_ = value;
    }
  }

  /// <summary>Field number for the "GBNJBNONIGC" field.</summary>
  public const int GBNJBNONIGCFieldNumber = 15;
  private bool gBNJBNONIGC_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool GBNJBNONIGC {
    get { return gBNJBNONIGC_; }
    set {
      gBNJBNONIGC_ = value;
    }
  }

  /// <summary>Field number for the "MOIKANDJPMJ" field.</summary>
  public const int MOIKANDJPMJFieldNumber = 4;
  private bool mOIKANDJPMJ_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool MOIKANDJPMJ {
    get { return mOIKANDJPMJ_; }
    set {
      mOIKANDJPMJ_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as EvtAvatarEnterFocusNotify);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(EvtAvatarEnterFocusNotify other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(FocusForward, other.FocusForward)) return false;
    if (KDPFLFOPIIJ != other.KDPFLFOPIIJ) return false;
    if (AKBIIAHOHLB != other.AKBIIAHOHLB) return false;
    if (HGKPAMDOJFG != other.HGKPAMDOJFG) return false;
    if (ECMCNFDKECN != other.ECMCNFDKECN) return false;
    if (ForwardType != other.ForwardType) return false;
    if (NOGNKKJAIJC != other.NOGNKKJAIJC) return false;
    if (EntityId != other.EntityId) return false;
    if (DJGHAHJAILG != other.DJGHAHJAILG) return false;
    if (OOGEIOCDENJ != other.OOGEIOCDENJ) return false;
    if (CIHGJJLNFIN != other.CIHGJJLNFIN) return false;
    if (GBEEOHGICAN != other.GBEEOHGICAN) return false;
    if (GBNJBNONIGC != other.GBNJBNONIGC) return false;
    if (MOIKANDJPMJ != other.MOIKANDJPMJ) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (focusForward_ != null) hash ^= FocusForward.GetHashCode();
    if (KDPFLFOPIIJ != false) hash ^= KDPFLFOPIIJ.GetHashCode();
    if (AKBIIAHOHLB != false) hash ^= AKBIIAHOHLB.GetHashCode();
    if (HGKPAMDOJFG != false) hash ^= HGKPAMDOJFG.GetHashCode();
    if (ECMCNFDKECN != false) hash ^= ECMCNFDKECN.GetHashCode();
    if (ForwardType != global::ForwardType.ForwardLocal) hash ^= ForwardType.GetHashCode();
    if (NOGNKKJAIJC != 0) hash ^= NOGNKKJAIJC.GetHashCode();
    if (EntityId != 0) hash ^= EntityId.GetHashCode();
    if (DJGHAHJAILG != false) hash ^= DJGHAHJAILG.GetHashCode();
    if (OOGEIOCDENJ != false) hash ^= OOGEIOCDENJ.GetHashCode();
    if (CIHGJJLNFIN != false) hash ^= CIHGJJLNFIN.GetHashCode();
    if (GBEEOHGICAN != false) hash ^= GBEEOHGICAN.GetHashCode();
    if (GBNJBNONIGC != false) hash ^= GBNJBNONIGC.GetHashCode();
    if (MOIKANDJPMJ != false) hash ^= MOIKANDJPMJ.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (GBEEOHGICAN != false) {
      output.WriteRawTag(8);
      output.WriteBool(GBEEOHGICAN);
    }
    if (OOGEIOCDENJ != false) {
      output.WriteRawTag(16);
      output.WriteBool(OOGEIOCDENJ);
    }
    if (NOGNKKJAIJC != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(NOGNKKJAIJC);
    }
    if (MOIKANDJPMJ != false) {
      output.WriteRawTag(32);
      output.WriteBool(MOIKANDJPMJ);
    }
    if (ForwardType != global::ForwardType.ForwardLocal) {
      output.WriteRawTag(48);
      output.WriteEnum((int) ForwardType);
    }
    if (AKBIIAHOHLB != false) {
      output.WriteRawTag(56);
      output.WriteBool(AKBIIAHOHLB);
    }
    if (EntityId != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(EntityId);
    }
    if (DJGHAHJAILG != false) {
      output.WriteRawTag(72);
      output.WriteBool(DJGHAHJAILG);
    }
    if (HGKPAMDOJFG != false) {
      output.WriteRawTag(80);
      output.WriteBool(HGKPAMDOJFG);
    }
    if (KDPFLFOPIIJ != false) {
      output.WriteRawTag(88);
      output.WriteBool(KDPFLFOPIIJ);
    }
    if (ECMCNFDKECN != false) {
      output.WriteRawTag(96);
      output.WriteBool(ECMCNFDKECN);
    }
    if (CIHGJJLNFIN != false) {
      output.WriteRawTag(104);
      output.WriteBool(CIHGJJLNFIN);
    }
    if (focusForward_ != null) {
      output.WriteRawTag(114);
      output.WriteMessage(FocusForward);
    }
    if (GBNJBNONIGC != false) {
      output.WriteRawTag(120);
      output.WriteBool(GBNJBNONIGC);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (GBEEOHGICAN != false) {
      output.WriteRawTag(8);
      output.WriteBool(GBEEOHGICAN);
    }
    if (OOGEIOCDENJ != false) {
      output.WriteRawTag(16);
      output.WriteBool(OOGEIOCDENJ);
    }
    if (NOGNKKJAIJC != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(NOGNKKJAIJC);
    }
    if (MOIKANDJPMJ != false) {
      output.WriteRawTag(32);
      output.WriteBool(MOIKANDJPMJ);
    }
    if (ForwardType != global::ForwardType.ForwardLocal) {
      output.WriteRawTag(48);
      output.WriteEnum((int) ForwardType);
    }
    if (AKBIIAHOHLB != false) {
      output.WriteRawTag(56);
      output.WriteBool(AKBIIAHOHLB);
    }
    if (EntityId != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(EntityId);
    }
    if (DJGHAHJAILG != false) {
      output.WriteRawTag(72);
      output.WriteBool(DJGHAHJAILG);
    }
    if (HGKPAMDOJFG != false) {
      output.WriteRawTag(80);
      output.WriteBool(HGKPAMDOJFG);
    }
    if (KDPFLFOPIIJ != false) {
      output.WriteRawTag(88);
      output.WriteBool(KDPFLFOPIIJ);
    }
    if (ECMCNFDKECN != false) {
      output.WriteRawTag(96);
      output.WriteBool(ECMCNFDKECN);
    }
    if (CIHGJJLNFIN != false) {
      output.WriteRawTag(104);
      output.WriteBool(CIHGJJLNFIN);
    }
    if (focusForward_ != null) {
      output.WriteRawTag(114);
      output.WriteMessage(FocusForward);
    }
    if (GBNJBNONIGC != false) {
      output.WriteRawTag(120);
      output.WriteBool(GBNJBNONIGC);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (focusForward_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(FocusForward);
    }
    if (KDPFLFOPIIJ != false) {
      size += 1 + 1;
    }
    if (AKBIIAHOHLB != false) {
      size += 1 + 1;
    }
    if (HGKPAMDOJFG != false) {
      size += 1 + 1;
    }
    if (ECMCNFDKECN != false) {
      size += 1 + 1;
    }
    if (ForwardType != global::ForwardType.ForwardLocal) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ForwardType);
    }
    if (NOGNKKJAIJC != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(NOGNKKJAIJC);
    }
    if (EntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EntityId);
    }
    if (DJGHAHJAILG != false) {
      size += 1 + 1;
    }
    if (OOGEIOCDENJ != false) {
      size += 1 + 1;
    }
    if (CIHGJJLNFIN != false) {
      size += 1 + 1;
    }
    if (GBEEOHGICAN != false) {
      size += 1 + 1;
    }
    if (GBNJBNONIGC != false) {
      size += 1 + 1;
    }
    if (MOIKANDJPMJ != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(EvtAvatarEnterFocusNotify other) {
    if (other == null) {
      return;
    }
    if (other.focusForward_ != null) {
      if (focusForward_ == null) {
        FocusForward = new global::Vector();
      }
      FocusForward.MergeFrom(other.FocusForward);
    }
    if (other.KDPFLFOPIIJ != false) {
      KDPFLFOPIIJ = other.KDPFLFOPIIJ;
    }
    if (other.AKBIIAHOHLB != false) {
      AKBIIAHOHLB = other.AKBIIAHOHLB;
    }
    if (other.HGKPAMDOJFG != false) {
      HGKPAMDOJFG = other.HGKPAMDOJFG;
    }
    if (other.ECMCNFDKECN != false) {
      ECMCNFDKECN = other.ECMCNFDKECN;
    }
    if (other.ForwardType != global::ForwardType.ForwardLocal) {
      ForwardType = other.ForwardType;
    }
    if (other.NOGNKKJAIJC != 0) {
      NOGNKKJAIJC = other.NOGNKKJAIJC;
    }
    if (other.EntityId != 0) {
      EntityId = other.EntityId;
    }
    if (other.DJGHAHJAILG != false) {
      DJGHAHJAILG = other.DJGHAHJAILG;
    }
    if (other.OOGEIOCDENJ != false) {
      OOGEIOCDENJ = other.OOGEIOCDENJ;
    }
    if (other.CIHGJJLNFIN != false) {
      CIHGJJLNFIN = other.CIHGJJLNFIN;
    }
    if (other.GBEEOHGICAN != false) {
      GBEEOHGICAN = other.GBEEOHGICAN;
    }
    if (other.GBNJBNONIGC != false) {
      GBNJBNONIGC = other.GBNJBNONIGC;
    }
    if (other.MOIKANDJPMJ != false) {
      MOIKANDJPMJ = other.MOIKANDJPMJ;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          GBEEOHGICAN = input.ReadBool();
          break;
        }
        case 16: {
          OOGEIOCDENJ = input.ReadBool();
          break;
        }
        case 24: {
          NOGNKKJAIJC = input.ReadInt32();
          break;
        }
        case 32: {
          MOIKANDJPMJ = input.ReadBool();
          break;
        }
        case 48: {
          ForwardType = (global::ForwardType) input.ReadEnum();
          break;
        }
        case 56: {
          AKBIIAHOHLB = input.ReadBool();
          break;
        }
        case 64: {
          EntityId = input.ReadUInt32();
          break;
        }
        case 72: {
          DJGHAHJAILG = input.ReadBool();
          break;
        }
        case 80: {
          HGKPAMDOJFG = input.ReadBool();
          break;
        }
        case 88: {
          KDPFLFOPIIJ = input.ReadBool();
          break;
        }
        case 96: {
          ECMCNFDKECN = input.ReadBool();
          break;
        }
        case 104: {
          CIHGJJLNFIN = input.ReadBool();
          break;
        }
        case 114: {
          if (focusForward_ == null) {
            FocusForward = new global::Vector();
          }
          input.ReadMessage(FocusForward);
          break;
        }
        case 120: {
          GBNJBNONIGC = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          GBEEOHGICAN = input.ReadBool();
          break;
        }
        case 16: {
          OOGEIOCDENJ = input.ReadBool();
          break;
        }
        case 24: {
          NOGNKKJAIJC = input.ReadInt32();
          break;
        }
        case 32: {
          MOIKANDJPMJ = input.ReadBool();
          break;
        }
        case 48: {
          ForwardType = (global::ForwardType) input.ReadEnum();
          break;
        }
        case 56: {
          AKBIIAHOHLB = input.ReadBool();
          break;
        }
        case 64: {
          EntityId = input.ReadUInt32();
          break;
        }
        case 72: {
          DJGHAHJAILG = input.ReadBool();
          break;
        }
        case 80: {
          HGKPAMDOJFG = input.ReadBool();
          break;
        }
        case 88: {
          KDPFLFOPIIJ = input.ReadBool();
          break;
        }
        case 96: {
          ECMCNFDKECN = input.ReadBool();
          break;
        }
        case 104: {
          CIHGJJLNFIN = input.ReadBool();
          break;
        }
        case 114: {
          if (focusForward_ == null) {
            FocusForward = new global::Vector();
          }
          input.ReadMessage(FocusForward);
          break;
        }
        case 120: {
          GBNJBNONIGC = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
