// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GadgetInteractReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GadgetInteractReq.proto</summary>
public static partial class GadgetInteractReqReflection {

  #region Descriptor
  /// <summary>File descriptor for GadgetInteractReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GadgetInteractReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChdHYWRnZXRJbnRlcmFjdFJlcS5wcm90bxoRSW50ZXJPcFR5cGUucHJvdG8a",
          "E1Jlc2luQ29zdFR5cGUucHJvdG8iqAIKEUdhZGdldEludGVyYWN0UmVxEicK",
          "D3Jlc2luX2Nvc3RfdHlwZRgCIAEoDjIOLlJlc2luQ29zdFR5cGUSEQoJZ2Fk",
          "Z2V0X2lkGAMgASgNEh0KB29wX3R5cGUYDSABKA4yDC5JbnRlck9wVHlwZRIW",
          "Cg51aV9pbnRlcmFjdF9pZBgEIAEoDRITCgtQTURQTkxKQUZKRxgFIAEoDRIT",
          "CgtBQ0pGT0tES01ORRgJIAEoCBIdChVpc191c2VfY29uZGVuc2VfcmVzaW4Y",
          "CiABKAgSEwoLQUNGT0xBTEhDTk8YDiABKAgSEwoLS0dJT0ROQUdEQ0kYDCAB",
          "KAgSGAoQZ2FkZ2V0X2VudGl0eV9pZBgIIAEoDRITCgtFR0dQQUhPRE1GTxgH",
          "IAEoDUIbChllbXUuZ3Jhc3NjdXR0ZXIubmV0LnByb3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::InterOpTypeReflection.Descriptor, global::ResinCostTypeReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GadgetInteractReq), global::GadgetInteractReq.Parser, new[]{ "ResinCostType", "GadgetId", "OpType", "UiInteractId", "PMDPNLJAFJG", "ACJFOKDKMNE", "IsUseCondenseResin", "ACFOLALHCNO", "KGIODNAGDCI", "GadgetEntityId", "EGGPAHODMFO" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.1
/// CmdID: 29784
/// </summary>
public sealed partial class GadgetInteractReq : pb::IMessage<GadgetInteractReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GadgetInteractReq> _parser = new pb::MessageParser<GadgetInteractReq>(() => new GadgetInteractReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GadgetInteractReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GadgetInteractReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GadgetInteractReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GadgetInteractReq(GadgetInteractReq other) : this() {
    resinCostType_ = other.resinCostType_;
    gadgetId_ = other.gadgetId_;
    opType_ = other.opType_;
    uiInteractId_ = other.uiInteractId_;
    pMDPNLJAFJG_ = other.pMDPNLJAFJG_;
    aCJFOKDKMNE_ = other.aCJFOKDKMNE_;
    isUseCondenseResin_ = other.isUseCondenseResin_;
    aCFOLALHCNO_ = other.aCFOLALHCNO_;
    kGIODNAGDCI_ = other.kGIODNAGDCI_;
    gadgetEntityId_ = other.gadgetEntityId_;
    eGGPAHODMFO_ = other.eGGPAHODMFO_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GadgetInteractReq Clone() {
    return new GadgetInteractReq(this);
  }

  /// <summary>Field number for the "resin_cost_type" field.</summary>
  public const int ResinCostTypeFieldNumber = 2;
  private global::ResinCostType resinCostType_ = global::ResinCostType.None;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::ResinCostType ResinCostType {
    get { return resinCostType_; }
    set {
      resinCostType_ = value;
    }
  }

  /// <summary>Field number for the "gadget_id" field.</summary>
  public const int GadgetIdFieldNumber = 3;
  private uint gadgetId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GadgetId {
    get { return gadgetId_; }
    set {
      gadgetId_ = value;
    }
  }

  /// <summary>Field number for the "op_type" field.</summary>
  public const int OpTypeFieldNumber = 13;
  private global::InterOpType opType_ = global::InterOpType.InterOpFinish;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::InterOpType OpType {
    get { return opType_; }
    set {
      opType_ = value;
    }
  }

  /// <summary>Field number for the "ui_interact_id" field.</summary>
  public const int UiInteractIdFieldNumber = 4;
  private uint uiInteractId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint UiInteractId {
    get { return uiInteractId_; }
    set {
      uiInteractId_ = value;
    }
  }

  /// <summary>Field number for the "PMDPNLJAFJG" field.</summary>
  public const int PMDPNLJAFJGFieldNumber = 5;
  private uint pMDPNLJAFJG_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint PMDPNLJAFJG {
    get { return pMDPNLJAFJG_; }
    set {
      pMDPNLJAFJG_ = value;
    }
  }

  /// <summary>Field number for the "ACJFOKDKMNE" field.</summary>
  public const int ACJFOKDKMNEFieldNumber = 9;
  private bool aCJFOKDKMNE_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool ACJFOKDKMNE {
    get { return aCJFOKDKMNE_; }
    set {
      aCJFOKDKMNE_ = value;
    }
  }

  /// <summary>Field number for the "is_use_condense_resin" field.</summary>
  public const int IsUseCondenseResinFieldNumber = 10;
  private bool isUseCondenseResin_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsUseCondenseResin {
    get { return isUseCondenseResin_; }
    set {
      isUseCondenseResin_ = value;
    }
  }

  /// <summary>Field number for the "ACFOLALHCNO" field.</summary>
  public const int ACFOLALHCNOFieldNumber = 14;
  private bool aCFOLALHCNO_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool ACFOLALHCNO {
    get { return aCFOLALHCNO_; }
    set {
      aCFOLALHCNO_ = value;
    }
  }

  /// <summary>Field number for the "KGIODNAGDCI" field.</summary>
  public const int KGIODNAGDCIFieldNumber = 12;
  private bool kGIODNAGDCI_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool KGIODNAGDCI {
    get { return kGIODNAGDCI_; }
    set {
      kGIODNAGDCI_ = value;
    }
  }

  /// <summary>Field number for the "gadget_entity_id" field.</summary>
  public const int GadgetEntityIdFieldNumber = 8;
  private uint gadgetEntityId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GadgetEntityId {
    get { return gadgetEntityId_; }
    set {
      gadgetEntityId_ = value;
    }
  }

  /// <summary>Field number for the "EGGPAHODMFO" field.</summary>
  public const int EGGPAHODMFOFieldNumber = 7;
  private uint eGGPAHODMFO_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint EGGPAHODMFO {
    get { return eGGPAHODMFO_; }
    set {
      eGGPAHODMFO_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GadgetInteractReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GadgetInteractReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ResinCostType != other.ResinCostType) return false;
    if (GadgetId != other.GadgetId) return false;
    if (OpType != other.OpType) return false;
    if (UiInteractId != other.UiInteractId) return false;
    if (PMDPNLJAFJG != other.PMDPNLJAFJG) return false;
    if (ACJFOKDKMNE != other.ACJFOKDKMNE) return false;
    if (IsUseCondenseResin != other.IsUseCondenseResin) return false;
    if (ACFOLALHCNO != other.ACFOLALHCNO) return false;
    if (KGIODNAGDCI != other.KGIODNAGDCI) return false;
    if (GadgetEntityId != other.GadgetEntityId) return false;
    if (EGGPAHODMFO != other.EGGPAHODMFO) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (ResinCostType != global::ResinCostType.None) hash ^= ResinCostType.GetHashCode();
    if (GadgetId != 0) hash ^= GadgetId.GetHashCode();
    if (OpType != global::InterOpType.InterOpFinish) hash ^= OpType.GetHashCode();
    if (UiInteractId != 0) hash ^= UiInteractId.GetHashCode();
    if (PMDPNLJAFJG != 0) hash ^= PMDPNLJAFJG.GetHashCode();
    if (ACJFOKDKMNE != false) hash ^= ACJFOKDKMNE.GetHashCode();
    if (IsUseCondenseResin != false) hash ^= IsUseCondenseResin.GetHashCode();
    if (ACFOLALHCNO != false) hash ^= ACFOLALHCNO.GetHashCode();
    if (KGIODNAGDCI != false) hash ^= KGIODNAGDCI.GetHashCode();
    if (GadgetEntityId != 0) hash ^= GadgetEntityId.GetHashCode();
    if (EGGPAHODMFO != 0) hash ^= EGGPAHODMFO.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (ResinCostType != global::ResinCostType.None) {
      output.WriteRawTag(16);
      output.WriteEnum((int) ResinCostType);
    }
    if (GadgetId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(GadgetId);
    }
    if (UiInteractId != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(UiInteractId);
    }
    if (PMDPNLJAFJG != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(PMDPNLJAFJG);
    }
    if (EGGPAHODMFO != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(EGGPAHODMFO);
    }
    if (GadgetEntityId != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(GadgetEntityId);
    }
    if (ACJFOKDKMNE != false) {
      output.WriteRawTag(72);
      output.WriteBool(ACJFOKDKMNE);
    }
    if (IsUseCondenseResin != false) {
      output.WriteRawTag(80);
      output.WriteBool(IsUseCondenseResin);
    }
    if (KGIODNAGDCI != false) {
      output.WriteRawTag(96);
      output.WriteBool(KGIODNAGDCI);
    }
    if (OpType != global::InterOpType.InterOpFinish) {
      output.WriteRawTag(104);
      output.WriteEnum((int) OpType);
    }
    if (ACFOLALHCNO != false) {
      output.WriteRawTag(112);
      output.WriteBool(ACFOLALHCNO);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (ResinCostType != global::ResinCostType.None) {
      output.WriteRawTag(16);
      output.WriteEnum((int) ResinCostType);
    }
    if (GadgetId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(GadgetId);
    }
    if (UiInteractId != 0) {
      output.WriteRawTag(32);
      output.WriteUInt32(UiInteractId);
    }
    if (PMDPNLJAFJG != 0) {
      output.WriteRawTag(40);
      output.WriteUInt32(PMDPNLJAFJG);
    }
    if (EGGPAHODMFO != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(EGGPAHODMFO);
    }
    if (GadgetEntityId != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(GadgetEntityId);
    }
    if (ACJFOKDKMNE != false) {
      output.WriteRawTag(72);
      output.WriteBool(ACJFOKDKMNE);
    }
    if (IsUseCondenseResin != false) {
      output.WriteRawTag(80);
      output.WriteBool(IsUseCondenseResin);
    }
    if (KGIODNAGDCI != false) {
      output.WriteRawTag(96);
      output.WriteBool(KGIODNAGDCI);
    }
    if (OpType != global::InterOpType.InterOpFinish) {
      output.WriteRawTag(104);
      output.WriteEnum((int) OpType);
    }
    if (ACFOLALHCNO != false) {
      output.WriteRawTag(112);
      output.WriteBool(ACFOLALHCNO);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (ResinCostType != global::ResinCostType.None) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ResinCostType);
    }
    if (GadgetId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GadgetId);
    }
    if (OpType != global::InterOpType.InterOpFinish) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OpType);
    }
    if (UiInteractId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(UiInteractId);
    }
    if (PMDPNLJAFJG != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PMDPNLJAFJG);
    }
    if (ACJFOKDKMNE != false) {
      size += 1 + 1;
    }
    if (IsUseCondenseResin != false) {
      size += 1 + 1;
    }
    if (ACFOLALHCNO != false) {
      size += 1 + 1;
    }
    if (KGIODNAGDCI != false) {
      size += 1 + 1;
    }
    if (GadgetEntityId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GadgetEntityId);
    }
    if (EGGPAHODMFO != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EGGPAHODMFO);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GadgetInteractReq other) {
    if (other == null) {
      return;
    }
    if (other.ResinCostType != global::ResinCostType.None) {
      ResinCostType = other.ResinCostType;
    }
    if (other.GadgetId != 0) {
      GadgetId = other.GadgetId;
    }
    if (other.OpType != global::InterOpType.InterOpFinish) {
      OpType = other.OpType;
    }
    if (other.UiInteractId != 0) {
      UiInteractId = other.UiInteractId;
    }
    if (other.PMDPNLJAFJG != 0) {
      PMDPNLJAFJG = other.PMDPNLJAFJG;
    }
    if (other.ACJFOKDKMNE != false) {
      ACJFOKDKMNE = other.ACJFOKDKMNE;
    }
    if (other.IsUseCondenseResin != false) {
      IsUseCondenseResin = other.IsUseCondenseResin;
    }
    if (other.ACFOLALHCNO != false) {
      ACFOLALHCNO = other.ACFOLALHCNO;
    }
    if (other.KGIODNAGDCI != false) {
      KGIODNAGDCI = other.KGIODNAGDCI;
    }
    if (other.GadgetEntityId != 0) {
      GadgetEntityId = other.GadgetEntityId;
    }
    if (other.EGGPAHODMFO != 0) {
      EGGPAHODMFO = other.EGGPAHODMFO;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 16: {
          ResinCostType = (global::ResinCostType) input.ReadEnum();
          break;
        }
        case 24: {
          GadgetId = input.ReadUInt32();
          break;
        }
        case 32: {
          UiInteractId = input.ReadUInt32();
          break;
        }
        case 40: {
          PMDPNLJAFJG = input.ReadUInt32();
          break;
        }
        case 56: {
          EGGPAHODMFO = input.ReadUInt32();
          break;
        }
        case 64: {
          GadgetEntityId = input.ReadUInt32();
          break;
        }
        case 72: {
          ACJFOKDKMNE = input.ReadBool();
          break;
        }
        case 80: {
          IsUseCondenseResin = input.ReadBool();
          break;
        }
        case 96: {
          KGIODNAGDCI = input.ReadBool();
          break;
        }
        case 104: {
          OpType = (global::InterOpType) input.ReadEnum();
          break;
        }
        case 112: {
          ACFOLALHCNO = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 16: {
          ResinCostType = (global::ResinCostType) input.ReadEnum();
          break;
        }
        case 24: {
          GadgetId = input.ReadUInt32();
          break;
        }
        case 32: {
          UiInteractId = input.ReadUInt32();
          break;
        }
        case 40: {
          PMDPNLJAFJG = input.ReadUInt32();
          break;
        }
        case 56: {
          EGGPAHODMFO = input.ReadUInt32();
          break;
        }
        case 64: {
          GadgetEntityId = input.ReadUInt32();
          break;
        }
        case 72: {
          ACJFOKDKMNE = input.ReadBool();
          break;
        }
        case 80: {
          IsUseCondenseResin = input.ReadBool();
          break;
        }
        case 96: {
          KGIODNAGDCI = input.ReadBool();
          break;
        }
        case 104: {
          OpType = (global::InterOpType) input.ReadEnum();
          break;
        }
        case 112: {
          ACFOLALHCNO = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
