// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GetGachaInfoRsp.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GetGachaInfoRsp.proto</summary>
public static partial class GetGachaInfoRspReflection {

  #region Descriptor
  /// <summary>File descriptor for GetGachaInfoRsp.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GetGachaInfoRspReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVHZXRHYWNoYUluZm9Sc3AucHJvdG8aD0dhY2hhSW5mby5wcm90byK9AQoP",
          "R2V0R2FjaGFJbmZvUnNwEiMKD2dhY2hhX2luZm9fbGlzdBgKIAMoCzIKLkdh",
          "Y2hhSW5mbxIgChhpc191bmRlcl9taW5vcnNfcmVzdHJpY3QYCSABKAgSIQoZ",
          "aXNfdW5kZXJfZ2VuZXJhbF9yZXN0cmljdBgMIAEoCBIPCgdyZXRjb2RlGAIg",
          "ASgFEhkKEWRhaWx5X2dhY2hhX3RpbWVzGAEgASgNEhQKDGdhY2hhX3JhbmRv",
          "bRgHIAEoDUIbChllbXUuZ3Jhc3NjdXR0ZXIubmV0LnByb3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::GachaInfoReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::GetGachaInfoRsp), global::GetGachaInfoRsp.Parser, new[]{ "GachaInfoList", "IsUnderMinorsRestrict", "IsUnderGeneralRestrict", "Retcode", "DailyGachaTimes", "GachaRandom" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.1
/// CmdID: 25921
/// </summary>
public sealed partial class GetGachaInfoRsp : pb::IMessage<GetGachaInfoRsp>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<GetGachaInfoRsp> _parser = new pb::MessageParser<GetGachaInfoRsp>(() => new GetGachaInfoRsp());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<GetGachaInfoRsp> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GetGachaInfoRspReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGachaInfoRsp() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGachaInfoRsp(GetGachaInfoRsp other) : this() {
    gachaInfoList_ = other.gachaInfoList_.Clone();
    isUnderMinorsRestrict_ = other.isUnderMinorsRestrict_;
    isUnderGeneralRestrict_ = other.isUnderGeneralRestrict_;
    retcode_ = other.retcode_;
    dailyGachaTimes_ = other.dailyGachaTimes_;
    gachaRandom_ = other.gachaRandom_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public GetGachaInfoRsp Clone() {
    return new GetGachaInfoRsp(this);
  }

  /// <summary>Field number for the "gacha_info_list" field.</summary>
  public const int GachaInfoListFieldNumber = 10;
  private static readonly pb::FieldCodec<global::GachaInfo> _repeated_gachaInfoList_codec
      = pb::FieldCodec.ForMessage(82, global::GachaInfo.Parser);
  private readonly pbc::RepeatedField<global::GachaInfo> gachaInfoList_ = new pbc::RepeatedField<global::GachaInfo>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::GachaInfo> GachaInfoList {
    get { return gachaInfoList_; }
  }

  /// <summary>Field number for the "is_under_minors_restrict" field.</summary>
  public const int IsUnderMinorsRestrictFieldNumber = 9;
  private bool isUnderMinorsRestrict_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsUnderMinorsRestrict {
    get { return isUnderMinorsRestrict_; }
    set {
      isUnderMinorsRestrict_ = value;
    }
  }

  /// <summary>Field number for the "is_under_general_restrict" field.</summary>
  public const int IsUnderGeneralRestrictFieldNumber = 12;
  private bool isUnderGeneralRestrict_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsUnderGeneralRestrict {
    get { return isUnderGeneralRestrict_; }
    set {
      isUnderGeneralRestrict_ = value;
    }
  }

  /// <summary>Field number for the "retcode" field.</summary>
  public const int RetcodeFieldNumber = 2;
  private int retcode_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Retcode {
    get { return retcode_; }
    set {
      retcode_ = value;
    }
  }

  /// <summary>Field number for the "daily_gacha_times" field.</summary>
  public const int DailyGachaTimesFieldNumber = 1;
  private uint dailyGachaTimes_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint DailyGachaTimes {
    get { return dailyGachaTimes_; }
    set {
      dailyGachaTimes_ = value;
    }
  }

  /// <summary>Field number for the "gacha_random" field.</summary>
  public const int GachaRandomFieldNumber = 7;
  private uint gachaRandom_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint GachaRandom {
    get { return gachaRandom_; }
    set {
      gachaRandom_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as GetGachaInfoRsp);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(GetGachaInfoRsp other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!gachaInfoList_.Equals(other.gachaInfoList_)) return false;
    if (IsUnderMinorsRestrict != other.IsUnderMinorsRestrict) return false;
    if (IsUnderGeneralRestrict != other.IsUnderGeneralRestrict) return false;
    if (Retcode != other.Retcode) return false;
    if (DailyGachaTimes != other.DailyGachaTimes) return false;
    if (GachaRandom != other.GachaRandom) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= gachaInfoList_.GetHashCode();
    if (IsUnderMinorsRestrict != false) hash ^= IsUnderMinorsRestrict.GetHashCode();
    if (IsUnderGeneralRestrict != false) hash ^= IsUnderGeneralRestrict.GetHashCode();
    if (Retcode != 0) hash ^= Retcode.GetHashCode();
    if (DailyGachaTimes != 0) hash ^= DailyGachaTimes.GetHashCode();
    if (GachaRandom != 0) hash ^= GachaRandom.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (DailyGachaTimes != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(DailyGachaTimes);
    }
    if (Retcode != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Retcode);
    }
    if (GachaRandom != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(GachaRandom);
    }
    if (IsUnderMinorsRestrict != false) {
      output.WriteRawTag(72);
      output.WriteBool(IsUnderMinorsRestrict);
    }
    gachaInfoList_.WriteTo(output, _repeated_gachaInfoList_codec);
    if (IsUnderGeneralRestrict != false) {
      output.WriteRawTag(96);
      output.WriteBool(IsUnderGeneralRestrict);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (DailyGachaTimes != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(DailyGachaTimes);
    }
    if (Retcode != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Retcode);
    }
    if (GachaRandom != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(GachaRandom);
    }
    if (IsUnderMinorsRestrict != false) {
      output.WriteRawTag(72);
      output.WriteBool(IsUnderMinorsRestrict);
    }
    gachaInfoList_.WriteTo(ref output, _repeated_gachaInfoList_codec);
    if (IsUnderGeneralRestrict != false) {
      output.WriteRawTag(96);
      output.WriteBool(IsUnderGeneralRestrict);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += gachaInfoList_.CalculateSize(_repeated_gachaInfoList_codec);
    if (IsUnderMinorsRestrict != false) {
      size += 1 + 1;
    }
    if (IsUnderGeneralRestrict != false) {
      size += 1 + 1;
    }
    if (Retcode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Retcode);
    }
    if (DailyGachaTimes != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DailyGachaTimes);
    }
    if (GachaRandom != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(GachaRandom);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(GetGachaInfoRsp other) {
    if (other == null) {
      return;
    }
    gachaInfoList_.Add(other.gachaInfoList_);
    if (other.IsUnderMinorsRestrict != false) {
      IsUnderMinorsRestrict = other.IsUnderMinorsRestrict;
    }
    if (other.IsUnderGeneralRestrict != false) {
      IsUnderGeneralRestrict = other.IsUnderGeneralRestrict;
    }
    if (other.Retcode != 0) {
      Retcode = other.Retcode;
    }
    if (other.DailyGachaTimes != 0) {
      DailyGachaTimes = other.DailyGachaTimes;
    }
    if (other.GachaRandom != 0) {
      GachaRandom = other.GachaRandom;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          DailyGachaTimes = input.ReadUInt32();
          break;
        }
        case 16: {
          Retcode = input.ReadInt32();
          break;
        }
        case 56: {
          GachaRandom = input.ReadUInt32();
          break;
        }
        case 72: {
          IsUnderMinorsRestrict = input.ReadBool();
          break;
        }
        case 82: {
          gachaInfoList_.AddEntriesFrom(input, _repeated_gachaInfoList_codec);
          break;
        }
        case 96: {
          IsUnderGeneralRestrict = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          DailyGachaTimes = input.ReadUInt32();
          break;
        }
        case 16: {
          Retcode = input.ReadInt32();
          break;
        }
        case 56: {
          GachaRandom = input.ReadUInt32();
          break;
        }
        case 72: {
          IsUnderMinorsRestrict = input.ReadBool();
          break;
        }
        case 82: {
          gachaInfoList_.AddEntriesFrom(ref input, _repeated_gachaInfoList_codec);
          break;
        }
        case 96: {
          IsUnderGeneralRestrict = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
