// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HomeBlockArrangementInfo.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from HomeBlockArrangementInfo.proto</summary>
public static partial class HomeBlockArrangementInfoReflection {

  #region Descriptor
  /// <summary>File descriptor for HomeBlockArrangementInfo.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static HomeBlockArrangementInfoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch5Ib21lQmxvY2tBcnJhbmdlbWVudEluZm8ucHJvdG8aEUhvbWVOcGNEYXRh",
          "LnByb3RvGhdIb21lRnVybml0dXJlRGF0YS5wcm90bxoiSG9tZUZ1cm5pdHVy",
          "ZUN1c3RvbVN1aXRlRGF0YS5wcm90bxoUSG9tZUFuaW1hbERhdGEucHJvdG8a",
          "HEhvbWVGdXJuaXR1cmVTdWl0ZURhdGEucHJvdG8aFldlZWtlbmREamlubklu",
          "Zm8ucHJvdG8aGEhvbWVCbG9ja0ZpZWxkRGF0YS5wcm90bxoZSG9tZUJsb2Nr",
          "RG90UGF0dGVybi5wcm90bxocSG9tZUZ1cm5pdHVyZUdyb3VwRGF0YS5wcm90",
          "byLIBAoYSG9tZUJsb2NrQXJyYW5nZW1lbnRJbmZvEhMKC2lzX3VubG9ja2Vk",
          "GAogASgIEhUKDWNvbWZvcnRfdmFsdWUYDCABKA0SEAoIYmxvY2tfaWQYDyAB",
          "KA0SJgoLRUhLR09OTElBSkIYASADKAsyES5XZWVrZW5kRGppbm5JbmZvEi4K",
          "EGRvdF9wYXR0ZXJuX2xpc3QYBSADKAsyFC5Ib21lQmxvY2tEb3RQYXR0ZXJu",
          "EisKEmRlcGxveV9hbmltYWxfbGlzdBgGIAMoCzIPLkhvbWVBbmltYWxEYXRh",
          "EiUKD2RlcGxveV9ucGNfbGlzdBgEIAMoCzIMLkhvbWVOcGNEYXRhEkIKG2Z1",
          "cm5pdHVyZV9jdXN0b21fc3VpdGVfbGlzdBgLIAMoCzIdLkhvbWVGdXJuaXR1",
          "cmVDdXN0b21TdWl0ZURhdGESNQoUZnVybml0dXJlX3N1aXRlX2xpc3QYAyAD",
          "KAsyFy5Ib21lRnVybml0dXJlU3VpdGVEYXRhEjUKGXBlcnNpc3RlbnRfZnVy",
          "bml0dXJlX2xpc3QYDiADKAsyEi5Ib21lRnVybml0dXJlRGF0YRIwChRkZXBs",
          "b3lfZnVybml1cmVfbGlzdBgIIAMoCzISLkhvbWVGdXJuaXR1cmVEYXRhEjUK",
          "FGZ1cm5pdHVyZV9ncm91cF9saXN0GAkgAygLMhcuSG9tZUZ1cm5pdHVyZUdy",
          "b3VwRGF0YRInCgpmaWVsZF9saXN0GA0gAygLMhMuSG9tZUJsb2NrRmllbGRE",
          "YXRhQhsKGWVtdS5ncmFzc2N1dHRlci5uZXQucHJvdG9iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::HomeNpcDataReflection.Descriptor, global::HomeFurnitureDataReflection.Descriptor, global::HomeFurnitureCustomSuiteDataReflection.Descriptor, global::HomeAnimalDataReflection.Descriptor, global::HomeFurnitureSuiteDataReflection.Descriptor, global::WeekendDjinnInfoReflection.Descriptor, global::HomeBlockFieldDataReflection.Descriptor, global::HomeBlockDotPatternReflection.Descriptor, global::HomeFurnitureGroupDataReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::HomeBlockArrangementInfo), global::HomeBlockArrangementInfo.Parser, new[]{ "IsUnlocked", "ComfortValue", "BlockId", "EHKGONLIAJB", "DotPatternList", "DeployAnimalList", "DeployNpcList", "FurnitureCustomSuiteList", "FurnitureSuiteList", "PersistentFurnitureList", "DeployFurniureList", "FurnitureGroupList", "FieldList" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.0
/// </summary>
public sealed partial class HomeBlockArrangementInfo : pb::IMessage<HomeBlockArrangementInfo>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<HomeBlockArrangementInfo> _parser = new pb::MessageParser<HomeBlockArrangementInfo>(() => new HomeBlockArrangementInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<HomeBlockArrangementInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::HomeBlockArrangementInfoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HomeBlockArrangementInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HomeBlockArrangementInfo(HomeBlockArrangementInfo other) : this() {
    isUnlocked_ = other.isUnlocked_;
    comfortValue_ = other.comfortValue_;
    blockId_ = other.blockId_;
    eHKGONLIAJB_ = other.eHKGONLIAJB_.Clone();
    dotPatternList_ = other.dotPatternList_.Clone();
    deployAnimalList_ = other.deployAnimalList_.Clone();
    deployNpcList_ = other.deployNpcList_.Clone();
    furnitureCustomSuiteList_ = other.furnitureCustomSuiteList_.Clone();
    furnitureSuiteList_ = other.furnitureSuiteList_.Clone();
    persistentFurnitureList_ = other.persistentFurnitureList_.Clone();
    deployFurniureList_ = other.deployFurniureList_.Clone();
    furnitureGroupList_ = other.furnitureGroupList_.Clone();
    fieldList_ = other.fieldList_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public HomeBlockArrangementInfo Clone() {
    return new HomeBlockArrangementInfo(this);
  }

  /// <summary>Field number for the "is_unlocked" field.</summary>
  public const int IsUnlockedFieldNumber = 10;
  private bool isUnlocked_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsUnlocked {
    get { return isUnlocked_; }
    set {
      isUnlocked_ = value;
    }
  }

  /// <summary>Field number for the "comfort_value" field.</summary>
  public const int ComfortValueFieldNumber = 12;
  private uint comfortValue_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ComfortValue {
    get { return comfortValue_; }
    set {
      comfortValue_ = value;
    }
  }

  /// <summary>Field number for the "block_id" field.</summary>
  public const int BlockIdFieldNumber = 15;
  private uint blockId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint BlockId {
    get { return blockId_; }
    set {
      blockId_ = value;
    }
  }

  /// <summary>Field number for the "EHKGONLIAJB" field.</summary>
  public const int EHKGONLIAJBFieldNumber = 1;
  private static readonly pb::FieldCodec<global::WeekendDjinnInfo> _repeated_eHKGONLIAJB_codec
      = pb::FieldCodec.ForMessage(10, global::WeekendDjinnInfo.Parser);
  private readonly pbc::RepeatedField<global::WeekendDjinnInfo> eHKGONLIAJB_ = new pbc::RepeatedField<global::WeekendDjinnInfo>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::WeekendDjinnInfo> EHKGONLIAJB {
    get { return eHKGONLIAJB_; }
  }

  /// <summary>Field number for the "dot_pattern_list" field.</summary>
  public const int DotPatternListFieldNumber = 5;
  private static readonly pb::FieldCodec<global::HomeBlockDotPattern> _repeated_dotPatternList_codec
      = pb::FieldCodec.ForMessage(42, global::HomeBlockDotPattern.Parser);
  private readonly pbc::RepeatedField<global::HomeBlockDotPattern> dotPatternList_ = new pbc::RepeatedField<global::HomeBlockDotPattern>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeBlockDotPattern> DotPatternList {
    get { return dotPatternList_; }
  }

  /// <summary>Field number for the "deploy_animal_list" field.</summary>
  public const int DeployAnimalListFieldNumber = 6;
  private static readonly pb::FieldCodec<global::HomeAnimalData> _repeated_deployAnimalList_codec
      = pb::FieldCodec.ForMessage(50, global::HomeAnimalData.Parser);
  private readonly pbc::RepeatedField<global::HomeAnimalData> deployAnimalList_ = new pbc::RepeatedField<global::HomeAnimalData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeAnimalData> DeployAnimalList {
    get { return deployAnimalList_; }
  }

  /// <summary>Field number for the "deploy_npc_list" field.</summary>
  public const int DeployNpcListFieldNumber = 4;
  private static readonly pb::FieldCodec<global::HomeNpcData> _repeated_deployNpcList_codec
      = pb::FieldCodec.ForMessage(34, global::HomeNpcData.Parser);
  private readonly pbc::RepeatedField<global::HomeNpcData> deployNpcList_ = new pbc::RepeatedField<global::HomeNpcData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeNpcData> DeployNpcList {
    get { return deployNpcList_; }
  }

  /// <summary>Field number for the "furniture_custom_suite_list" field.</summary>
  public const int FurnitureCustomSuiteListFieldNumber = 11;
  private static readonly pb::FieldCodec<global::HomeFurnitureCustomSuiteData> _repeated_furnitureCustomSuiteList_codec
      = pb::FieldCodec.ForMessage(90, global::HomeFurnitureCustomSuiteData.Parser);
  private readonly pbc::RepeatedField<global::HomeFurnitureCustomSuiteData> furnitureCustomSuiteList_ = new pbc::RepeatedField<global::HomeFurnitureCustomSuiteData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeFurnitureCustomSuiteData> FurnitureCustomSuiteList {
    get { return furnitureCustomSuiteList_; }
  }

  /// <summary>Field number for the "furniture_suite_list" field.</summary>
  public const int FurnitureSuiteListFieldNumber = 3;
  private static readonly pb::FieldCodec<global::HomeFurnitureSuiteData> _repeated_furnitureSuiteList_codec
      = pb::FieldCodec.ForMessage(26, global::HomeFurnitureSuiteData.Parser);
  private readonly pbc::RepeatedField<global::HomeFurnitureSuiteData> furnitureSuiteList_ = new pbc::RepeatedField<global::HomeFurnitureSuiteData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeFurnitureSuiteData> FurnitureSuiteList {
    get { return furnitureSuiteList_; }
  }

  /// <summary>Field number for the "persistent_furniture_list" field.</summary>
  public const int PersistentFurnitureListFieldNumber = 14;
  private static readonly pb::FieldCodec<global::HomeFurnitureData> _repeated_persistentFurnitureList_codec
      = pb::FieldCodec.ForMessage(114, global::HomeFurnitureData.Parser);
  private readonly pbc::RepeatedField<global::HomeFurnitureData> persistentFurnitureList_ = new pbc::RepeatedField<global::HomeFurnitureData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeFurnitureData> PersistentFurnitureList {
    get { return persistentFurnitureList_; }
  }

  /// <summary>Field number for the "deploy_furniure_list" field.</summary>
  public const int DeployFurniureListFieldNumber = 8;
  private static readonly pb::FieldCodec<global::HomeFurnitureData> _repeated_deployFurniureList_codec
      = pb::FieldCodec.ForMessage(66, global::HomeFurnitureData.Parser);
  private readonly pbc::RepeatedField<global::HomeFurnitureData> deployFurniureList_ = new pbc::RepeatedField<global::HomeFurnitureData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeFurnitureData> DeployFurniureList {
    get { return deployFurniureList_; }
  }

  /// <summary>Field number for the "furniture_group_list" field.</summary>
  public const int FurnitureGroupListFieldNumber = 9;
  private static readonly pb::FieldCodec<global::HomeFurnitureGroupData> _repeated_furnitureGroupList_codec
      = pb::FieldCodec.ForMessage(74, global::HomeFurnitureGroupData.Parser);
  private readonly pbc::RepeatedField<global::HomeFurnitureGroupData> furnitureGroupList_ = new pbc::RepeatedField<global::HomeFurnitureGroupData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeFurnitureGroupData> FurnitureGroupList {
    get { return furnitureGroupList_; }
  }

  /// <summary>Field number for the "field_list" field.</summary>
  public const int FieldListFieldNumber = 13;
  private static readonly pb::FieldCodec<global::HomeBlockFieldData> _repeated_fieldList_codec
      = pb::FieldCodec.ForMessage(106, global::HomeBlockFieldData.Parser);
  private readonly pbc::RepeatedField<global::HomeBlockFieldData> fieldList_ = new pbc::RepeatedField<global::HomeBlockFieldData>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::HomeBlockFieldData> FieldList {
    get { return fieldList_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as HomeBlockArrangementInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(HomeBlockArrangementInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IsUnlocked != other.IsUnlocked) return false;
    if (ComfortValue != other.ComfortValue) return false;
    if (BlockId != other.BlockId) return false;
    if(!eHKGONLIAJB_.Equals(other.eHKGONLIAJB_)) return false;
    if(!dotPatternList_.Equals(other.dotPatternList_)) return false;
    if(!deployAnimalList_.Equals(other.deployAnimalList_)) return false;
    if(!deployNpcList_.Equals(other.deployNpcList_)) return false;
    if(!furnitureCustomSuiteList_.Equals(other.furnitureCustomSuiteList_)) return false;
    if(!furnitureSuiteList_.Equals(other.furnitureSuiteList_)) return false;
    if(!persistentFurnitureList_.Equals(other.persistentFurnitureList_)) return false;
    if(!deployFurniureList_.Equals(other.deployFurniureList_)) return false;
    if(!furnitureGroupList_.Equals(other.furnitureGroupList_)) return false;
    if(!fieldList_.Equals(other.fieldList_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (IsUnlocked != false) hash ^= IsUnlocked.GetHashCode();
    if (ComfortValue != 0) hash ^= ComfortValue.GetHashCode();
    if (BlockId != 0) hash ^= BlockId.GetHashCode();
    hash ^= eHKGONLIAJB_.GetHashCode();
    hash ^= dotPatternList_.GetHashCode();
    hash ^= deployAnimalList_.GetHashCode();
    hash ^= deployNpcList_.GetHashCode();
    hash ^= furnitureCustomSuiteList_.GetHashCode();
    hash ^= furnitureSuiteList_.GetHashCode();
    hash ^= persistentFurnitureList_.GetHashCode();
    hash ^= deployFurniureList_.GetHashCode();
    hash ^= furnitureGroupList_.GetHashCode();
    hash ^= fieldList_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    eHKGONLIAJB_.WriteTo(output, _repeated_eHKGONLIAJB_codec);
    furnitureSuiteList_.WriteTo(output, _repeated_furnitureSuiteList_codec);
    deployNpcList_.WriteTo(output, _repeated_deployNpcList_codec);
    dotPatternList_.WriteTo(output, _repeated_dotPatternList_codec);
    deployAnimalList_.WriteTo(output, _repeated_deployAnimalList_codec);
    deployFurniureList_.WriteTo(output, _repeated_deployFurniureList_codec);
    furnitureGroupList_.WriteTo(output, _repeated_furnitureGroupList_codec);
    if (IsUnlocked != false) {
      output.WriteRawTag(80);
      output.WriteBool(IsUnlocked);
    }
    furnitureCustomSuiteList_.WriteTo(output, _repeated_furnitureCustomSuiteList_codec);
    if (ComfortValue != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(ComfortValue);
    }
    fieldList_.WriteTo(output, _repeated_fieldList_codec);
    persistentFurnitureList_.WriteTo(output, _repeated_persistentFurnitureList_codec);
    if (BlockId != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(BlockId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    eHKGONLIAJB_.WriteTo(ref output, _repeated_eHKGONLIAJB_codec);
    furnitureSuiteList_.WriteTo(ref output, _repeated_furnitureSuiteList_codec);
    deployNpcList_.WriteTo(ref output, _repeated_deployNpcList_codec);
    dotPatternList_.WriteTo(ref output, _repeated_dotPatternList_codec);
    deployAnimalList_.WriteTo(ref output, _repeated_deployAnimalList_codec);
    deployFurniureList_.WriteTo(ref output, _repeated_deployFurniureList_codec);
    furnitureGroupList_.WriteTo(ref output, _repeated_furnitureGroupList_codec);
    if (IsUnlocked != false) {
      output.WriteRawTag(80);
      output.WriteBool(IsUnlocked);
    }
    furnitureCustomSuiteList_.WriteTo(ref output, _repeated_furnitureCustomSuiteList_codec);
    if (ComfortValue != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(ComfortValue);
    }
    fieldList_.WriteTo(ref output, _repeated_fieldList_codec);
    persistentFurnitureList_.WriteTo(ref output, _repeated_persistentFurnitureList_codec);
    if (BlockId != 0) {
      output.WriteRawTag(120);
      output.WriteUInt32(BlockId);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (IsUnlocked != false) {
      size += 1 + 1;
    }
    if (ComfortValue != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ComfortValue);
    }
    if (BlockId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BlockId);
    }
    size += eHKGONLIAJB_.CalculateSize(_repeated_eHKGONLIAJB_codec);
    size += dotPatternList_.CalculateSize(_repeated_dotPatternList_codec);
    size += deployAnimalList_.CalculateSize(_repeated_deployAnimalList_codec);
    size += deployNpcList_.CalculateSize(_repeated_deployNpcList_codec);
    size += furnitureCustomSuiteList_.CalculateSize(_repeated_furnitureCustomSuiteList_codec);
    size += furnitureSuiteList_.CalculateSize(_repeated_furnitureSuiteList_codec);
    size += persistentFurnitureList_.CalculateSize(_repeated_persistentFurnitureList_codec);
    size += deployFurniureList_.CalculateSize(_repeated_deployFurniureList_codec);
    size += furnitureGroupList_.CalculateSize(_repeated_furnitureGroupList_codec);
    size += fieldList_.CalculateSize(_repeated_fieldList_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(HomeBlockArrangementInfo other) {
    if (other == null) {
      return;
    }
    if (other.IsUnlocked != false) {
      IsUnlocked = other.IsUnlocked;
    }
    if (other.ComfortValue != 0) {
      ComfortValue = other.ComfortValue;
    }
    if (other.BlockId != 0) {
      BlockId = other.BlockId;
    }
    eHKGONLIAJB_.Add(other.eHKGONLIAJB_);
    dotPatternList_.Add(other.dotPatternList_);
    deployAnimalList_.Add(other.deployAnimalList_);
    deployNpcList_.Add(other.deployNpcList_);
    furnitureCustomSuiteList_.Add(other.furnitureCustomSuiteList_);
    furnitureSuiteList_.Add(other.furnitureSuiteList_);
    persistentFurnitureList_.Add(other.persistentFurnitureList_);
    deployFurniureList_.Add(other.deployFurniureList_);
    furnitureGroupList_.Add(other.furnitureGroupList_);
    fieldList_.Add(other.fieldList_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          eHKGONLIAJB_.AddEntriesFrom(input, _repeated_eHKGONLIAJB_codec);
          break;
        }
        case 26: {
          furnitureSuiteList_.AddEntriesFrom(input, _repeated_furnitureSuiteList_codec);
          break;
        }
        case 34: {
          deployNpcList_.AddEntriesFrom(input, _repeated_deployNpcList_codec);
          break;
        }
        case 42: {
          dotPatternList_.AddEntriesFrom(input, _repeated_dotPatternList_codec);
          break;
        }
        case 50: {
          deployAnimalList_.AddEntriesFrom(input, _repeated_deployAnimalList_codec);
          break;
        }
        case 66: {
          deployFurniureList_.AddEntriesFrom(input, _repeated_deployFurniureList_codec);
          break;
        }
        case 74: {
          furnitureGroupList_.AddEntriesFrom(input, _repeated_furnitureGroupList_codec);
          break;
        }
        case 80: {
          IsUnlocked = input.ReadBool();
          break;
        }
        case 90: {
          furnitureCustomSuiteList_.AddEntriesFrom(input, _repeated_furnitureCustomSuiteList_codec);
          break;
        }
        case 96: {
          ComfortValue = input.ReadUInt32();
          break;
        }
        case 106: {
          fieldList_.AddEntriesFrom(input, _repeated_fieldList_codec);
          break;
        }
        case 114: {
          persistentFurnitureList_.AddEntriesFrom(input, _repeated_persistentFurnitureList_codec);
          break;
        }
        case 120: {
          BlockId = input.ReadUInt32();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          eHKGONLIAJB_.AddEntriesFrom(ref input, _repeated_eHKGONLIAJB_codec);
          break;
        }
        case 26: {
          furnitureSuiteList_.AddEntriesFrom(ref input, _repeated_furnitureSuiteList_codec);
          break;
        }
        case 34: {
          deployNpcList_.AddEntriesFrom(ref input, _repeated_deployNpcList_codec);
          break;
        }
        case 42: {
          dotPatternList_.AddEntriesFrom(ref input, _repeated_dotPatternList_codec);
          break;
        }
        case 50: {
          deployAnimalList_.AddEntriesFrom(ref input, _repeated_deployAnimalList_codec);
          break;
        }
        case 66: {
          deployFurniureList_.AddEntriesFrom(ref input, _repeated_deployFurniureList_codec);
          break;
        }
        case 74: {
          furnitureGroupList_.AddEntriesFrom(ref input, _repeated_furnitureGroupList_codec);
          break;
        }
        case 80: {
          IsUnlocked = input.ReadBool();
          break;
        }
        case 90: {
          furnitureCustomSuiteList_.AddEntriesFrom(ref input, _repeated_furnitureCustomSuiteList_codec);
          break;
        }
        case 96: {
          ComfortValue = input.ReadUInt32();
          break;
        }
        case 106: {
          fieldList_.AddEntriesFrom(ref input, _repeated_fieldList_codec);
          break;
        }
        case 114: {
          persistentFurnitureList_.AddEntriesFrom(ref input, _repeated_persistentFurnitureList_codec);
          break;
        }
        case 120: {
          BlockId = input.ReadUInt32();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
