// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: LifeByOwnerType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from LifeByOwnerType.proto</summary>
public static partial class LifeByOwnerTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for LifeByOwnerType.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static LifeByOwnerTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVMaWZlQnlPd25lclR5cGUucHJvdG8qVQoPTGlmZUJ5T3duZXJUeXBlEhYK",
          "EkxJRkVfQllfT1dORVJfTk9ORRAAEhQKEExJRkVfQllfT1dORVJfVjIQARIU",
          "ChBMSUZFX0JZX09XTkVSX1YzEAJCGwoZZW11LmdyYXNzY3V0dGVyLm5ldC5w",
          "cm90b2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LifeByOwnerType), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// Version: 6.0
/// </summary>
public enum LifeByOwnerType {
  [pbr::OriginalName("LIFE_BY_OWNER_NONE")] LifeByOwnerNone = 0,
  [pbr::OriginalName("LIFE_BY_OWNER_V2")] LifeByOwnerV2 = 1,
  [pbr::OriginalName("LIFE_BY_OWNER_V3")] LifeByOwnerV3 = 2,
}

#endregion


#endregion Designer generated code
