// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MpSettingType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MpSettingType.proto</summary>
public static partial class MpSettingTypeReflection {

  #region Descriptor
  /// <summary>File descriptor for MpSettingType.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MpSettingTypeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNNcFNldHRpbmdUeXBlLnByb3RvKpEBCg1NcFNldHRpbmdUeXBlEiUKIU1w",
          "U2V0dGluZ1R5cGVfTVBfU0VUVElOR19OT19FTlRFUhAAEikKJU1wU2V0dGlu",
          "Z1R5cGVfTVBfU0VUVElOR19FTlRFUl9GUkVFTFkQARIuCipNcFNldHRpbmdU",
          "eXBlX01QX1NFVFRJTkdfRU5URVJfQUZURVJfQVBQTFkQAkIbChllbXUuZ3Jh",
          "c3NjdXR0ZXIubmV0LnByb3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MpSettingType), }, null, null));
  }
  #endregion

}
#region Enums
public enum MpSettingType {
  [pbr::OriginalName("MpSettingType_MP_SETTING_NO_ENTER")] MpSettingNoEnter = 0,
  [pbr::OriginalName("MpSettingType_MP_SETTING_ENTER_FREELY")] MpSettingEnterFreely = 1,
  [pbr::OriginalName("MpSettingType_MP_SETTING_ENTER_AFTER_APPLY")] MpSettingEnterAfterApply = 2,
}

#endregion


#endregion Designer generated code
