// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PingReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PingReq.proto</summary>
public static partial class PingReqReflection {

  #region Descriptor
  /// <summary>File descriptor for PingReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PingReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg1QaW5nUmVxLnByb3RvIqkBCgdQaW5nUmVxEhMKC1BLSUZISE5LSE5QGAEg",
          "ASgMEhMKC0tNT0VER09DT09KGA8gASgMEhMKC0dKR0pERU1ETUlLGAggASgE",
          "EhMKC2NsaWVudF90aW1lGAMgASgNEgsKA3NlcRgLIAEoDRIPCgd1ZV90aW1l",
          "GAYgASgCEhMKC0hCTFBHSktNTEVIGAcgASgNEhcKD3RvdGFsX3RpY2tfdGlt",
          "ZRgKIAEoAUIbChllbXUuZ3Jhc3NjdXR0ZXIubmV0LnByb3RvYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::PingReq), global::PingReq.Parser, new[]{ "PKIFHHNKHNP", "KMOEDGOCOOJ", "GJGJDEMDMIK", "ClientTime", "Seq", "UeTime", "HBLPGJKMLEH", "TotalTickTime" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class PingReq : pb::IMessage<PingReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PingReq> _parser = new pb::MessageParser<PingReq>(() => new PingReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PingReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::PingReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingReq(PingReq other) : this() {
    pKIFHHNKHNP_ = other.pKIFHHNKHNP_;
    kMOEDGOCOOJ_ = other.kMOEDGOCOOJ_;
    gJGJDEMDMIK_ = other.gJGJDEMDMIK_;
    clientTime_ = other.clientTime_;
    seq_ = other.seq_;
    ueTime_ = other.ueTime_;
    hBLPGJKMLEH_ = other.hBLPGJKMLEH_;
    totalTickTime_ = other.totalTickTime_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PingReq Clone() {
    return new PingReq(this);
  }

  /// <summary>Field number for the "PKIFHHNKHNP" field.</summary>
  public const int PKIFHHNKHNPFieldNumber = 1;
  private pb::ByteString pKIFHHNKHNP_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString PKIFHHNKHNP {
    get { return pKIFHHNKHNP_; }
    set {
      pKIFHHNKHNP_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "KMOEDGOCOOJ" field.</summary>
  public const int KMOEDGOCOOJFieldNumber = 15;
  private pb::ByteString kMOEDGOCOOJ_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pb::ByteString KMOEDGOCOOJ {
    get { return kMOEDGOCOOJ_; }
    set {
      kMOEDGOCOOJ_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "GJGJDEMDMIK" field.</summary>
  public const int GJGJDEMDMIKFieldNumber = 8;
  private ulong gJGJDEMDMIK_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ulong GJGJDEMDMIK {
    get { return gJGJDEMDMIK_; }
    set {
      gJGJDEMDMIK_ = value;
    }
  }

  /// <summary>Field number for the "client_time" field.</summary>
  public const int ClientTimeFieldNumber = 3;
  private uint clientTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint ClientTime {
    get { return clientTime_; }
    set {
      clientTime_ = value;
    }
  }

  /// <summary>Field number for the "seq" field.</summary>
  public const int SeqFieldNumber = 11;
  private uint seq_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint Seq {
    get { return seq_; }
    set {
      seq_ = value;
    }
  }

  /// <summary>Field number for the "ue_time" field.</summary>
  public const int UeTimeFieldNumber = 6;
  private float ueTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public float UeTime {
    get { return ueTime_; }
    set {
      ueTime_ = value;
    }
  }

  /// <summary>Field number for the "HBLPGJKMLEH" field.</summary>
  public const int HBLPGJKMLEHFieldNumber = 7;
  private uint hBLPGJKMLEH_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint HBLPGJKMLEH {
    get { return hBLPGJKMLEH_; }
    set {
      hBLPGJKMLEH_ = value;
    }
  }

  /// <summary>Field number for the "total_tick_time" field.</summary>
  public const int TotalTickTimeFieldNumber = 10;
  private double totalTickTime_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double TotalTickTime {
    get { return totalTickTime_; }
    set {
      totalTickTime_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PingReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PingReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PKIFHHNKHNP != other.PKIFHHNKHNP) return false;
    if (KMOEDGOCOOJ != other.KMOEDGOCOOJ) return false;
    if (GJGJDEMDMIK != other.GJGJDEMDMIK) return false;
    if (ClientTime != other.ClientTime) return false;
    if (Seq != other.Seq) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(UeTime, other.UeTime)) return false;
    if (HBLPGJKMLEH != other.HBLPGJKMLEH) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TotalTickTime, other.TotalTickTime)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (PKIFHHNKHNP.Length != 0) hash ^= PKIFHHNKHNP.GetHashCode();
    if (KMOEDGOCOOJ.Length != 0) hash ^= KMOEDGOCOOJ.GetHashCode();
    if (GJGJDEMDMIK != 0UL) hash ^= GJGJDEMDMIK.GetHashCode();
    if (ClientTime != 0) hash ^= ClientTime.GetHashCode();
    if (Seq != 0) hash ^= Seq.GetHashCode();
    if (UeTime != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(UeTime);
    if (HBLPGJKMLEH != 0) hash ^= HBLPGJKMLEH.GetHashCode();
    if (TotalTickTime != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TotalTickTime);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (PKIFHHNKHNP.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(PKIFHHNKHNP);
    }
    if (ClientTime != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(ClientTime);
    }
    if (UeTime != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(UeTime);
    }
    if (HBLPGJKMLEH != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(HBLPGJKMLEH);
    }
    if (GJGJDEMDMIK != 0UL) {
      output.WriteRawTag(64);
      output.WriteUInt64(GJGJDEMDMIK);
    }
    if (TotalTickTime != 0D) {
      output.WriteRawTag(81);
      output.WriteDouble(TotalTickTime);
    }
    if (Seq != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(Seq);
    }
    if (KMOEDGOCOOJ.Length != 0) {
      output.WriteRawTag(122);
      output.WriteBytes(KMOEDGOCOOJ);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (PKIFHHNKHNP.Length != 0) {
      output.WriteRawTag(10);
      output.WriteBytes(PKIFHHNKHNP);
    }
    if (ClientTime != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(ClientTime);
    }
    if (UeTime != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(UeTime);
    }
    if (HBLPGJKMLEH != 0) {
      output.WriteRawTag(56);
      output.WriteUInt32(HBLPGJKMLEH);
    }
    if (GJGJDEMDMIK != 0UL) {
      output.WriteRawTag(64);
      output.WriteUInt64(GJGJDEMDMIK);
    }
    if (TotalTickTime != 0D) {
      output.WriteRawTag(81);
      output.WriteDouble(TotalTickTime);
    }
    if (Seq != 0) {
      output.WriteRawTag(88);
      output.WriteUInt32(Seq);
    }
    if (KMOEDGOCOOJ.Length != 0) {
      output.WriteRawTag(122);
      output.WriteBytes(KMOEDGOCOOJ);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (PKIFHHNKHNP.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(PKIFHHNKHNP);
    }
    if (KMOEDGOCOOJ.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeBytesSize(KMOEDGOCOOJ);
    }
    if (GJGJDEMDMIK != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(GJGJDEMDMIK);
    }
    if (ClientTime != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ClientTime);
    }
    if (Seq != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Seq);
    }
    if (UeTime != 0F) {
      size += 1 + 4;
    }
    if (HBLPGJKMLEH != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(HBLPGJKMLEH);
    }
    if (TotalTickTime != 0D) {
      size += 1 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PingReq other) {
    if (other == null) {
      return;
    }
    if (other.PKIFHHNKHNP.Length != 0) {
      PKIFHHNKHNP = other.PKIFHHNKHNP;
    }
    if (other.KMOEDGOCOOJ.Length != 0) {
      KMOEDGOCOOJ = other.KMOEDGOCOOJ;
    }
    if (other.GJGJDEMDMIK != 0UL) {
      GJGJDEMDMIK = other.GJGJDEMDMIK;
    }
    if (other.ClientTime != 0) {
      ClientTime = other.ClientTime;
    }
    if (other.Seq != 0) {
      Seq = other.Seq;
    }
    if (other.UeTime != 0F) {
      UeTime = other.UeTime;
    }
    if (other.HBLPGJKMLEH != 0) {
      HBLPGJKMLEH = other.HBLPGJKMLEH;
    }
    if (other.TotalTickTime != 0D) {
      TotalTickTime = other.TotalTickTime;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          PKIFHHNKHNP = input.ReadBytes();
          break;
        }
        case 24: {
          ClientTime = input.ReadUInt32();
          break;
        }
        case 53: {
          UeTime = input.ReadFloat();
          break;
        }
        case 56: {
          HBLPGJKMLEH = input.ReadUInt32();
          break;
        }
        case 64: {
          GJGJDEMDMIK = input.ReadUInt64();
          break;
        }
        case 81: {
          TotalTickTime = input.ReadDouble();
          break;
        }
        case 88: {
          Seq = input.ReadUInt32();
          break;
        }
        case 122: {
          KMOEDGOCOOJ = input.ReadBytes();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 10: {
          PKIFHHNKHNP = input.ReadBytes();
          break;
        }
        case 24: {
          ClientTime = input.ReadUInt32();
          break;
        }
        case 53: {
          UeTime = input.ReadFloat();
          break;
        }
        case 56: {
          HBLPGJKMLEH = input.ReadUInt32();
          break;
        }
        case 64: {
          GJGJDEMDMIK = input.ReadUInt64();
          break;
        }
        case 81: {
          TotalTickTime = input.ReadDouble();
          break;
        }
        case 88: {
          Seq = input.ReadUInt32();
          break;
        }
        case 122: {
          KMOEDGOCOOJ = input.ReadBytes();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
