// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PlayerDieOption.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from PlayerDieOption.proto</summary>
public static partial class PlayerDieOptionReflection {

  #region Descriptor
  /// <summary>File descriptor for PlayerDieOption.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static PlayerDieOptionReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVQbGF5ZXJEaWVPcHRpb24ucHJvdG8qXwoPUGxheWVyRGllT3B0aW9uEhAK",
          "DERJRV9PUFRfTk9ORRAAEhIKDkRJRV9PUFRfUkVQTEFZEAESEgoORElFX09Q",
          "VF9DQU5DRUwQAhISCg5ESUVfT1BUX1JFVklWRRADQhsKGWVtdS5ncmFzc2N1",
          "dHRlci5uZXQucHJvdG9iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PlayerDieOption), }, null, null));
  }
  #endregion

}
#region Enums
/// <summary>
/// Version: 6.0
/// </summary>
public enum PlayerDieOption {
  [pbr::OriginalName("DIE_OPT_NONE")] DieOptNone = 0,
  [pbr::OriginalName("DIE_OPT_REPLAY")] DieOptReplay = 1,
  [pbr::OriginalName("DIE_OPT_CANCEL")] DieOptCancel = 2,
  [pbr::OriginalName("DIE_OPT_REVIVE")] DieOptRevive = 3,
}

#endregion


#endregion Designer generated code
