// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: QuestTransmitReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from QuestTransmitReq.proto</summary>
public static partial class QuestTransmitReqReflection {

  #region Descriptor
  /// <summary>File descriptor for QuestTransmitReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static QuestTransmitReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZRdWVzdFRyYW5zbWl0UmVxLnByb3RvIokBChBRdWVzdFRyYW5zbWl0UmVx",
          "EhAKCHF1ZXN0X2lkGA0gASgNEhMKC0tHS0NFSURGTkVHGA4gASgIEhsKE3Rl",
          "bXBsYXRlX2xvYWRpbmdfaWQYCSABKA0SEAoIcG9pbnRfaWQYDCABKA0iHwoF",
          "Q21kSWQSCAoETk9ORRAAEgwKBkNNRF9JRBDS/gZCGwoZZW11LmdyYXNzY3V0",
          "dGVyLm5ldC5wcm90b2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::QuestTransmitReq), global::QuestTransmitReq.Parser, new[]{ "QuestId", "KGKCEIDFNEG", "TemplateLoadingId", "PointId" }, null, new[]{ typeof(global::QuestTransmitReq.Types.CmdId) }, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// Version: 6.0
/// CmdId: 5458
/// </summary>
public sealed partial class QuestTransmitReq : pb::IMessage<QuestTransmitReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<QuestTransmitReq> _parser = new pb::MessageParser<QuestTransmitReq>(() => new QuestTransmitReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<QuestTransmitReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::QuestTransmitReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public QuestTransmitReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public QuestTransmitReq(QuestTransmitReq other) : this() {
    questId_ = other.questId_;
    kGKCEIDFNEG_ = other.kGKCEIDFNEG_;
    templateLoadingId_ = other.templateLoadingId_;
    pointId_ = other.pointId_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public QuestTransmitReq Clone() {
    return new QuestTransmitReq(this);
  }

  /// <summary>Field number for the "quest_id" field.</summary>
  public const int QuestIdFieldNumber = 13;
  private uint questId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint QuestId {
    get { return questId_; }
    set {
      questId_ = value;
    }
  }

  /// <summary>Field number for the "KGKCEIDFNEG" field.</summary>
  public const int KGKCEIDFNEGFieldNumber = 14;
  private bool kGKCEIDFNEG_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool KGKCEIDFNEG {
    get { return kGKCEIDFNEG_; }
    set {
      kGKCEIDFNEG_ = value;
    }
  }

  /// <summary>Field number for the "template_loading_id" field.</summary>
  public const int TemplateLoadingIdFieldNumber = 9;
  private uint templateLoadingId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint TemplateLoadingId {
    get { return templateLoadingId_; }
    set {
      templateLoadingId_ = value;
    }
  }

  /// <summary>Field number for the "point_id" field.</summary>
  public const int PointIdFieldNumber = 12;
  private uint pointId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint PointId {
    get { return pointId_; }
    set {
      pointId_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as QuestTransmitReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(QuestTransmitReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (QuestId != other.QuestId) return false;
    if (KGKCEIDFNEG != other.KGKCEIDFNEG) return false;
    if (TemplateLoadingId != other.TemplateLoadingId) return false;
    if (PointId != other.PointId) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (QuestId != 0) hash ^= QuestId.GetHashCode();
    if (KGKCEIDFNEG != false) hash ^= KGKCEIDFNEG.GetHashCode();
    if (TemplateLoadingId != 0) hash ^= TemplateLoadingId.GetHashCode();
    if (PointId != 0) hash ^= PointId.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (TemplateLoadingId != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(TemplateLoadingId);
    }
    if (PointId != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(PointId);
    }
    if (QuestId != 0) {
      output.WriteRawTag(104);
      output.WriteUInt32(QuestId);
    }
    if (KGKCEIDFNEG != false) {
      output.WriteRawTag(112);
      output.WriteBool(KGKCEIDFNEG);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (TemplateLoadingId != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(TemplateLoadingId);
    }
    if (PointId != 0) {
      output.WriteRawTag(96);
      output.WriteUInt32(PointId);
    }
    if (QuestId != 0) {
      output.WriteRawTag(104);
      output.WriteUInt32(QuestId);
    }
    if (KGKCEIDFNEG != false) {
      output.WriteRawTag(112);
      output.WriteBool(KGKCEIDFNEG);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (QuestId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(QuestId);
    }
    if (KGKCEIDFNEG != false) {
      size += 1 + 1;
    }
    if (TemplateLoadingId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TemplateLoadingId);
    }
    if (PointId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PointId);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(QuestTransmitReq other) {
    if (other == null) {
      return;
    }
    if (other.QuestId != 0) {
      QuestId = other.QuestId;
    }
    if (other.KGKCEIDFNEG != false) {
      KGKCEIDFNEG = other.KGKCEIDFNEG;
    }
    if (other.TemplateLoadingId != 0) {
      TemplateLoadingId = other.TemplateLoadingId;
    }
    if (other.PointId != 0) {
      PointId = other.PointId;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 72: {
          TemplateLoadingId = input.ReadUInt32();
          break;
        }
        case 96: {
          PointId = input.ReadUInt32();
          break;
        }
        case 104: {
          QuestId = input.ReadUInt32();
          break;
        }
        case 112: {
          KGKCEIDFNEG = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 72: {
          TemplateLoadingId = input.ReadUInt32();
          break;
        }
        case 96: {
          PointId = input.ReadUInt32();
          break;
        }
        case 104: {
          QuestId = input.ReadUInt32();
          break;
        }
        case 112: {
          KGKCEIDFNEG = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the QuestTransmitReq message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    /// <summary>
    /// Version: 6.0
    /// </summary>
    public enum CmdId {
      [pbr::OriginalName("NONE")] None = 0,
      [pbr::OriginalName("CMD_ID")] CmdId = 114514,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
