// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: SetWidgetSlotReq.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SetWidgetSlotReq.proto</summary>
public static partial class SetWidgetSlotReqReflection {

  #region Descriptor
  /// <summary>File descriptor for SetWidgetSlotReq.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SetWidgetSlotReqReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZTZXRXaWRnZXRTbG90UmVxLnByb3RvGhNXaWRnZXRTbG90VGFnLnByb3Rv",
          "GhJXaWRnZXRTbG90T3AucHJvdG8ihQEKEFNldFdpZGdldFNsb3RSZXESIAoI",
          "dGFnX2xpc3QYCCADKA4yDi5XaWRnZXRTbG90VGFnEhMKC21hdGVyaWFsX2lk",
          "GAMgASgNEhkKAm9wGA8gASgOMg0uV2lkZ2V0U2xvdE9wIh8KBUNtZElkEggK",
          "BE5PTkUQABIMCgZDTURfSUQQ0v4GQhsKGWVtdS5ncmFzc2N1dHRlci5uZXQu",
          "cHJvdG9iBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::WidgetSlotTagReflection.Descriptor, global::WidgetSlotOpReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SetWidgetSlotReq), global::SetWidgetSlotReq.Parser, new[]{ "TagList", "MaterialId", "Op" }, null, new[]{ typeof(global::SetWidgetSlotReq.Types.CmdId) }, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// CmdID: 8693
/// </summary>
public sealed partial class SetWidgetSlotReq : pb::IMessage<SetWidgetSlotReq>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<SetWidgetSlotReq> _parser = new pb::MessageParser<SetWidgetSlotReq>(() => new SetWidgetSlotReq());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<SetWidgetSlotReq> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SetWidgetSlotReqReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SetWidgetSlotReq() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SetWidgetSlotReq(SetWidgetSlotReq other) : this() {
    tagList_ = other.tagList_.Clone();
    materialId_ = other.materialId_;
    op_ = other.op_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public SetWidgetSlotReq Clone() {
    return new SetWidgetSlotReq(this);
  }

  /// <summary>Field number for the "tag_list" field.</summary>
  public const int TagListFieldNumber = 8;
  private static readonly pb::FieldCodec<global::WidgetSlotTag> _repeated_tagList_codec
      = pb::FieldCodec.ForEnum(66, x => (int) x, x => (global::WidgetSlotTag) x);
  private readonly pbc::RepeatedField<global::WidgetSlotTag> tagList_ = new pbc::RepeatedField<global::WidgetSlotTag>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<global::WidgetSlotTag> TagList {
    get { return tagList_; }
  }

  /// <summary>Field number for the "material_id" field.</summary>
  public const int MaterialIdFieldNumber = 3;
  private uint materialId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public uint MaterialId {
    get { return materialId_; }
    set {
      materialId_ = value;
    }
  }

  /// <summary>Field number for the "op" field.</summary>
  public const int OpFieldNumber = 15;
  private global::WidgetSlotOp op_ = global::WidgetSlotOp.Attach;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public global::WidgetSlotOp Op {
    get { return op_; }
    set {
      op_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as SetWidgetSlotReq);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(SetWidgetSlotReq other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!tagList_.Equals(other.tagList_)) return false;
    if (MaterialId != other.MaterialId) return false;
    if (Op != other.Op) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= tagList_.GetHashCode();
    if (MaterialId != 0) hash ^= MaterialId.GetHashCode();
    if (Op != global::WidgetSlotOp.Attach) hash ^= Op.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (MaterialId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(MaterialId);
    }
    tagList_.WriteTo(output, _repeated_tagList_codec);
    if (Op != global::WidgetSlotOp.Attach) {
      output.WriteRawTag(120);
      output.WriteEnum((int) Op);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (MaterialId != 0) {
      output.WriteRawTag(24);
      output.WriteUInt32(MaterialId);
    }
    tagList_.WriteTo(ref output, _repeated_tagList_codec);
    if (Op != global::WidgetSlotOp.Attach) {
      output.WriteRawTag(120);
      output.WriteEnum((int) Op);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    size += tagList_.CalculateSize(_repeated_tagList_codec);
    if (MaterialId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaterialId);
    }
    if (Op != global::WidgetSlotOp.Attach) {
      size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Op);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(SetWidgetSlotReq other) {
    if (other == null) {
      return;
    }
    tagList_.Add(other.tagList_);
    if (other.MaterialId != 0) {
      MaterialId = other.MaterialId;
    }
    if (other.Op != global::WidgetSlotOp.Attach) {
      Op = other.Op;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 24: {
          MaterialId = input.ReadUInt32();
          break;
        }
        case 66:
        case 64: {
          tagList_.AddEntriesFrom(input, _repeated_tagList_codec);
          break;
        }
        case 120: {
          Op = (global::WidgetSlotOp) input.ReadEnum();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 24: {
          MaterialId = input.ReadUInt32();
          break;
        }
        case 66:
        case 64: {
          tagList_.AddEntriesFrom(ref input, _repeated_tagList_codec);
          break;
        }
        case 120: {
          Op = (global::WidgetSlotOp) input.ReadEnum();
          break;
        }
      }
    }
  }
  #endif

  #region Nested types
  /// <summary>Container for nested types declared in the SetWidgetSlotReq message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static partial class Types {
    /// <summary>
    /// Version: 6.0
    /// </summary>
    public enum CmdId {
      [pbr::OriginalName("NONE")] None = 0,
      [pbr::OriginalName("CMD_ID")] CmdId = 114514,
    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
